import { escapeCell } from './common.js';
import type { CommandSpec, DocStats, OptionSpec } from '@core/types/commandDocs.js';
/** Render a command's flag table, or `""` when it has no options. */
const renderOptionsTable = (options: OptionSpec[]): string => {
  if (options.length === 0) return '';
  const rows = options.map((o) => `| \`${escapeCell(o.flags)}\` | ${escapeCell(o.description)} |`);
  return ['', '| Flag | Description |', '| --- | --- |', ...rows].join('\n');
};
/** Render one command (heading + description + flag table) and, recursively, its subcommands. */
const renderCommand = (command: CommandSpec, level: number): string => {
  let usage = `launch ${command.path}`;
  if (command.args) usage = `launch ${command.path} ${command.args}`;
  const parts = [`${'#'.repeat(level)} \`${usage}\``, '', command.description];
  const table = renderOptionsTable(command.options);
  if (table) parts.push(table);
  for (const sub of command.subcommands) parts.push('', renderCommand(sub, level + 1));
  return parts.join('\n');
};
/** Render `docs/commands.md`: the generated header, the live-stats blockquote, and every command. */
export const renderCommandReference = (commands: CommandSpec[], stats: DocStats): string => {
  const header =
    '<!-- AUTOGENERATED by `pnpm docs:gen` - do not edit by hand; edit the commands, then regenerate. -->';
  const blockquote = `> Launch wraps **${stats.operations} App Store Connect & Google Play API operations** across **${stats.commands} commands**, guarded by **${stats.tests} tests**.`;
  const intro =
    'Generated from the `commander` definitions in `src/cli/` by `pnpm docs:gen` - edit the commands, then regenerate. For the curated overview, install, and configuration, see the [README](../README.md).';
  const commandMarkdown = commands.map((command) => renderCommand(command, 2)).join('\n\n');
  return `${header}\n\n# Launch command reference\n\n${blockquote}\n\n${intro}\n\n${commandMarkdown}\n`;
};
