/**
 * Renders `docs/commands.md`: the generated header, the live-stats blockquote, and every command +
 * flag table, walking {@link CommandSpec} recursively. The human-facing command reference half of the
 * docs (the AI-facing half is `./llmsTxt.ts`).
 */

import { escapeCell } from "./common.js";
import type { CommandSpec, DocStats, OptionSpec } from "./types.js";

/** Render a command's flag table, or `""` when it has no options. */
function renderOptionsTable(options: OptionSpec[]): string {
  if (options.length === 0) return "";
  const rows = options.map((o) => `| \`${escapeCell(o.flags)}\` | ${escapeCell(o.description)} |`);
  return ["", "| Flag | Description |", "| --- | --- |", ...rows].join("\n");
}

/** Render one command (heading + description + flag table) and, recursively, its subcommands. */
function renderCommand(command: CommandSpec, level: number): string {
  const usage = command.args ? `launch ${command.path} ${command.args}` : `launch ${command.path}`;
  const parts = [`${"#".repeat(level)} \`${usage}\``, "", command.description];
  const table = renderOptionsTable(command.options);
  if (table) parts.push(table);
  for (const sub of command.subcommands) parts.push("", renderCommand(sub, level + 1));
  return parts.join("\n");
}

/** Render `docs/commands.md`: the generated header, the live-stats blockquote, and every command. */
export function renderCommandReference(commands: CommandSpec[], stats: DocStats): string {
  const header =
    "<!-- AUTOGENERATED by `npm run docs:gen` — do not edit by hand; edit the commands, then regenerate. -->";
  const blockquote = `> Launch wraps **${stats.operations} App Store Connect & Google Play API operations** across **${stats.commands} commands**, guarded by **${stats.tests} tests**.`;
  const intro =
    "Generated from the `commander` definitions in `src/cli/` by `npm run docs:gen` — edit the commands, then regenerate. For the curated overview, install, and configuration, see the [README](../README.md).";
  const body = commands.map((command) => renderCommand(command, 2)).join("\n\n");
  return `${header}\n\n# Launch command reference\n\n${blockquote}\n\n${intro}\n\n${body}\n`;
}
