import { FileSystem, Path } from '@effect/platform';
import { Data, Effect, Schema } from 'effect';
import { errorMessage } from '../services/errorMessage.js';
import { createLogger, type Logger } from '../services/logger.js';
import { LaunchPaths, type LaunchPathsService } from '../services/paths.js';

const WORKFLOW_SEGMENTS = ['.github', 'workflows', 'launch.yml'] as const;
export const WORKFLOW_PATH = WORKFLOW_SEGMENTS.join('/');

export const CiCommandInputSchema = Schema.Struct({
  android: Schema.Boolean,
  force: Schema.Boolean,
});

export type CiCommandInput = Schema.Schema.Type<typeof CiCommandInputSchema>;

export type CiCommandFailure = Readonly<{
  readonly _tag: 'CiCommandFailure';
  readonly operation: string;
  readonly message: string;
  readonly cause?: unknown;
}>;

export const makeCiCommandFailure = Data.tagged<CiCommandFailure>('CiCommandFailure');

/** Render the generated workflow's credential instructions. */
const workflowHeader = (includeAndroid: boolean): string => {
  const headerLines = [
    '# Launch - build and ship to the App Store / Play from CI.',
    '#',
    "# Generated by `launch ci init`. GitHub's hosted runners are the no-local-Mac path for",
    '# occasional release builds. Trigger it from the Actions tab or by pushing a version tag.',
    '#',
    '# Required repository secrets - Settings -> Secrets and variables -> Actions:',
    '#   ASC_KEY_ID           App Store Connect API key id (Users & Access -> Integrations -> Keys)',
    '#   ASC_ISSUER_ID        the issuer id shown on that same page',
    '#   ASC_API_KEY_BASE64   base64 of your AuthKey_*.p8: base64 -i AuthKey_XXXX.p8 | pbcopy',
  ];
  if (includeAndroid) {
    headerLines.push(
      '#   PLAY_SERVICE_ACCOUNT_BASE64   base64 of your Play service-account .json',
      '#   ANDROID_KEYSTORE_BASE64       base64 of your upload keystore',
      '#   ANDROID_KEY_ALIAS             the key alias inside that keystore',
      '#   ANDROID_KEYSTORE_PASSWORD     the keystore password',
      '#   ANDROID_KEY_PASSWORD          the key password (often the same)',
    );
  }
  return headerLines.join('\n');
};

const WORKFLOW_TRIGGERS = `name: launch
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:`;

const IOS_JOB = `
  ios:
    name: Build & ship iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install app dependencies
        run: npm ci
      - name: Install Launch
        run: npm install --global launch-store
      - name: Decode the App Store Connect API key
        run: |
          mkdir -p "$RUNNER_TEMP/launch"
          printf '%s' "$ASC_API_KEY_BASE64" | base64 --decode > "$RUNNER_TEMP/launch/AuthKey.p8"
        env:
          ASC_API_KEY_BASE64: \${{ secrets.ASC_API_KEY_BASE64 }}
      - name: Build and upload to TestFlight
        run: |
          launch creds set-key --yes
          launch creds setup --yes
          launch doctor --yes
          launch build ios --yes
        env:
          ASC_KEY_ID: \${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: \${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY_PATH: \${{ runner.temp }}/launch/AuthKey.p8`;

const ANDROID_JOB = `
  android:
    name: Build & ship Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Install app dependencies
        run: npm ci
      - name: Install Launch
        run: npm install --global launch-store
      - name: Decode the Play service account and upload keystore
        run: |
          mkdir -p "$RUNNER_TEMP/launch"
          printf '%s' "$PLAY_SERVICE_ACCOUNT_BASE64" | base64 --decode > "$RUNNER_TEMP/launch/play.json"
          printf '%s' "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$RUNNER_TEMP/launch/upload.keystore"
        env:
          PLAY_SERVICE_ACCOUNT_BASE64: \${{ secrets.PLAY_SERVICE_ACCOUNT_BASE64 }}
          ANDROID_KEYSTORE_BASE64: \${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Build and upload to Google Play
        run: |
          launch creds set-key --platform android "$RUNNER_TEMP/launch/play.json" --yes
          launch creds setup --platform android --import "$RUNNER_TEMP/launch/upload.keystore" --alias "$ANDROID_KEY_ALIAS" --yes
          launch build android --yes
        env:
          PLAY_SERVICE_ACCOUNT: \${{ runner.temp }}/launch/play.json
          ANDROID_KEY_ALIAS: \${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: \${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: \${{ secrets.ANDROID_KEY_PASSWORD }}`;

/** Render the complete GitHub Actions workflow. */
export const workflowYaml = (includeAndroid: boolean): string => {
  let workflowJobs = IOS_JOB;
  if (includeAndroid) workflowJobs = `${IOS_JOB}\n${ANDROID_JOB}`;
  return `${workflowHeader(includeAndroid)}\n\n${WORKFLOW_TRIGGERS}\n${workflowJobs}\n`;
};

/** Write the CI workflow and explain its required repository secrets. */
export const ciCommandProgram = (
  rawCommandInput: unknown,
): Effect.Effect<
  void,
  CiCommandFailure,
  FileSystem.FileSystem | LaunchPathsService | Logger | Path.Path
> =>
  Effect.gen(function* () {
    const commandInput = yield* Schema.decodeUnknown(CiCommandInputSchema)(rawCommandInput);
    const launchPaths = yield* LaunchPaths;
    const pathService = yield* Path.Path;
    const fileSystem = yield* FileSystem.FileSystem;
    const workflowPath = pathService.join(launchPaths.workingDirectory, ...WORKFLOW_SEGMENTS);
    if ((yield* fileSystem.exists(workflowPath)) && !commandInput.force) {
      return yield* Effect.fail(
        makeCiCommandFailure({
          operation: 'write CI workflow',
          message: `${WORKFLOW_PATH} already exists. Re-run with --force to overwrite it.`,
        }),
      );
    }
    yield* fileSystem.makeDirectory(pathService.dirname(workflowPath), { recursive: true });
    yield* fileSystem.writeFileString(workflowPath, workflowYaml(commandInput.android));
    const logger = yield* createLogger(false);
    yield* logger.ok(`Wrote ${WORKFLOW_PATH}`);
    yield* logger.line(
      '\nSet these repository secrets (Settings -> Secrets and variables -> Actions):',
    );
    yield* logger.line('  - ASC_KEY_ID, ASC_ISSUER_ID');
    yield* logger.line('  - ASC_API_KEY_BASE64    base64 -i AuthKey_XXXX.p8 | pbcopy');
    if (commandInput.android) {
      yield* logger.line('  - PLAY_SERVICE_ACCOUNT_BASE64, ANDROID_KEYSTORE_BASE64');
      yield* logger.line('  - ANDROID_KEY_ALIAS, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_PASSWORD');
    }
    yield* logger.line('\nThen push a v* tag or use Run workflow to build and ship.');
  }).pipe(
    Effect.mapError((cause) => {
      if (cause._tag === 'CiCommandFailure') return cause;
      return makeCiCommandFailure({
        operation: 'scaffold CI workflow',
        message: errorMessage(cause),
        cause,
      });
    }),
  );
