import { describe, expect, it } from 'vitest';
import { CONSUMER_SKILLS, CONTRIBUTOR_RULES, CONTRIBUTOR_SKILLS } from './registry.js';
import { expectArrayElement, expectDefined } from '@testkit/assertions.testkit.js';
import {
  MANAGED_END,
  MANAGED_START,
  renderAgentsBlock,
  renderAmazonQBaseRule,
  renderAmazonQTaskRule,
  renderClaudeMemoryBlock,
  renderClaudeSkillFiles,
  renderClineBaseRule,
  renderClineTaskRule,
  renderContributorRule,
  renderContributorSkill,
  renderCopilotBlock,
  renderCursorBaseRule,
  renderCursorTaskRule,
  renderKiroSteering,
  renderWindsurfBaseRule,
  renderWindsurfTaskRule,
  spliceManagedBlock,
} from './render.js';

const skill = (skillId: string) =>
  expectDefined(
    CONSUMER_SKILLS.find((candidateSkill) => candidateSkill.id === skillId),
    `consumer skill ${skillId}`,
  );
const VERSION = '9.9.9';

describe('Claude skill rendering', () => {
  it('emits a single SKILL.md with name+description frontmatter and a version stamp for a small skill', () => {
    const files = renderClaudeSkillFiles(skill('launch-ship'), VERSION);
    expect(files.map((generatedFile) => generatedFile.path)).toEqual([
      '.claude/skills/launch-ship/SKILL.md',
    ]);
    const skillMarkdown = expectArrayElement(files, 0, 'files').body;
    expect(skillMarkdown.startsWith('---\nname: launch-ship\ndescription: ')).toBe(true);
    expect(skillMarkdown).toContain(`generated by launch v${VERSION}`);
    expect(skillMarkdown).toContain('`npx launch init`');
    expect(skillMarkdown).not.toContain('reference.md');
  });
  it('bundles a reference.md for the large store-config skill and points the SKILL.md at it', () => {
    const files = renderClaudeSkillFiles(skill('launch-store-config'), VERSION);
    expect(files.map((generatedFile) => generatedFile.path)).toEqual([
      '.claude/skills/launch-store-config/SKILL.md',
      '.claude/skills/launch-store-config/reference.md',
    ]);
    expect(expectArrayElement(files, 0, 'files').body).toContain('reference.md');
    expect(expectArrayElement(files, 1, 'files').body).toContain('| Command | What it does |');
  });
});

describe('Cursor / Windsurf / Cline / Amazon Q rule rendering', () => {
  it('makes the Cursor base rule always-on and includes the EAS map and the release guardrail', () => {
    const rule = renderCursorBaseRule(VERSION);
    expect(rule.path).toBe('.cursor/rules/launch.mdc');
    expect(rule.body).toContain('alwaysApply: true');
    expect(rule.body).toContain('EAS -> Launch');
    expect(rule.body).toContain('launch release');
  });
  it('makes each Cursor task rule description-driven (Agent-Requested), not always-on', () => {
    const rule = renderCursorTaskRule(skill('launch-release'), VERSION);
    expect(rule.path).toBe('.cursor/rules/launch-release.mdc');
    expect(rule.body).toContain('alwaysApply: false');
    expect(rule.body).toContain('description: ');
    expect(rule.body).toContain('`npx launch release ios`');
  });
  it('shares base + task shape across Windsurf, Cline, and Amazon Q paths', () => {
    expect(renderWindsurfBaseRule(VERSION).path).toBe('.windsurf/rules/launch.md');
    expect(renderWindsurfTaskRule(skill('launch-ship'), VERSION).path).toBe(
      '.windsurf/rules/launch-ship.md',
    );
    expect(renderClineBaseRule(VERSION).path).toBe('.cline/rules/launch.md');
    expect(renderClineTaskRule(skill('launch-ship'), VERSION).body).toContain(
      `generated by launch v${VERSION}`,
    );
    expect(renderAmazonQBaseRule(VERSION).path).toBe('.amazonq/rules/launch.md');
    expect(renderAmazonQTaskRule(skill('launch-ship'), VERSION).path).toBe(
      '.amazonq/rules/launch-ship.md',
    );
  });
  it('flattens store-config reference inline for non-Claude task rules', () => {
    const storeConfig = skill('launch-store-config');
    expect(renderCursorTaskRule(storeConfig, VERSION).body).toContain('| Command | What it does |');
    expect(renderWindsurfTaskRule(storeConfig, VERSION).body).toContain(
      '| Command | What it does |',
    );
  });
});

describe('AGENTS.md, CLAUDE.md, Copilot, and Kiro managed content', () => {
  it('wraps the AGENTS.md block in fences and flattens every task for Codex', () => {
    const block = renderAgentsBlock(VERSION);
    expect(block.startsWith(MANAGED_START)).toBe(true);
    expect(block.endsWith(MANAGED_END)).toBe(true);
    for (const consumerSkill of CONSUMER_SKILLS) {
      expect(block, `missing ${consumerSkill.id}`).toContain(consumerSkill.title);
    }
    expect(block).toContain('| Command | What it does |');
  });
  it('imports AGENTS.md and lists the skills in the CLAUDE.md block', () => {
    const block = renderClaudeMemoryBlock(VERSION);
    expect(block).toContain('@AGENTS.md');
    expect(block).toContain('`launch-ship`');
    expect(block.startsWith(MANAGED_START)).toBe(true);
  });
  it('fences the Copilot block and emits a single Kiro steering file', () => {
    const copilotBlock = renderCopilotBlock(VERSION);
    expect(copilotBlock.startsWith(MANAGED_START)).toBe(true);
    expect(copilotBlock).toContain('### Available workflows');
    const kiro = renderKiroSteering(VERSION);
    expect(kiro.path).toBe('.kiro/steering/launch.md');
    expect(kiro.body).toContain('## Common tasks');
  });
});

describe("spliceManagedBlock preserves the user's own content", () => {
  const block = `${MANAGED_START}\nNEW\n${MANAGED_END}`;
  it('returns just the block for an empty file', () => {
    expect(spliceManagedBlock('', block)).toBe(`${block}\n`);
  });
  it('appends below existing content when there are no fences yet', () => {
    const splicedMarkdown = spliceManagedBlock('# My app\n\nmy own rules\n', block);
    expect(splicedMarkdown).toContain('# My app');
    expect(splicedMarkdown).toContain('my own rules');
    expect(splicedMarkdown).toContain('NEW');
  });
  it('replaces only the fenced region, keeping text around it', () => {
    const existing = `# My app\n\n${MANAGED_START}\nOLD\n${MANAGED_END}\n\nfooter\n`;
    const splicedMarkdown = spliceManagedBlock(existing, block);
    expect(splicedMarkdown).toContain('# My app');
    expect(splicedMarkdown).toContain('footer');
    expect(splicedMarkdown).toContain('NEW');
    expect(splicedMarkdown).not.toContain('OLD');
  });
});

describe('contributor rules are committed without a version stamp', () => {
  it('renders the base rule as always-on with no generated-by stamp', () => {
    const file = renderContributorRule(
      expectArrayElement(CONTRIBUTOR_RULES, 0, 'CONTRIBUTOR_RULES'),
    );
    expect(file.path).toBe('.cursor/rules/launch.mdc');
    expect(file.body).toContain('alwaysApply: true');
    expect(file.body).not.toContain('generated by launch');
    expect(file.body).toContain('AGENTS.md');
  });
  it('emits the glob line for a path-scoped rule', () => {
    const providers = expectDefined(
      CONTRIBUTOR_RULES.find((rule) => rule.file === 'providers'),
      'providers contributor rule',
    );
    const file = renderContributorRule(providers);
    expect(file.body).toContain('globs: src/providers/**');
    expect(file.body).toContain('alwaysApply: false');
  });
});

describe('contributor Claude skills are committed without a version stamp', () => {
  const gate = expectDefined(
    CONTRIBUTOR_SKILLS.find((contributorSkill) => contributorSkill.id === 'run-the-gate'),
    'run-the-gate contributor skill',
  );
  it('renders a SKILL.md with name+description frontmatter, the recipe, and no generated-by stamp', () => {
    const file = renderContributorSkill(gate);
    expect(file.path).toBe('.claude/skills/run-the-gate/SKILL.md');
    expect(file.body.startsWith('---\nname: run-the-gate\ndescription: ')).toBe(true);
    expect(file.body).not.toContain('generated by launch');
    expect(file.body).toContain('## Use this when');
    expect(file.body).toContain('## Steps');
    expect(file.body).toContain('pnpm docs:check');
    expect(file.body).toContain('(../../../AGENTS.md)');
  });
  it('renders the skill-specific cautions block when a skill has cautions', () => {
    const provider = expectDefined(
      CONTRIBUTOR_SKILLS.find((contributorSkill) => contributorSkill.id === 'add-a-provider'),
      'add-a-provider contributor skill',
    );
    expect(renderContributorSkill(provider).body).toContain('## Cautions');
  });
});
