/**
 * Pure renderers that turn the {@link import("./registry.js") registry} into each agent's NATIVE file
 * format — no `fs`, no commander, so they stay trivially unit-testable.
 *
 * - {@link renderClaudeSkillFiles} → `.claude/skills/<id>/SKILL.md` (+ `reference.md` for large skills),
 *   following Claude's progressive-disclosure pattern (lean SKILL.md, heavy detail in a bundled file).
 * - {@link renderCursorBaseRule} / {@link renderCursorTaskRule} → `.cursor/rules/*.mdc` (the base rule is
 *   `alwaysApply`; task rules are description-driven / Agent-Requested).
 * - {@link renderAgentsBlock} / {@link renderClaudeMemoryBlock} → the managed sections spliced into a
 *   consumer's `AGENTS.md` (Codex + the `CLAUDE.md` import target) and `CLAUDE.md`.
 * - {@link renderContributorRule} → the committed `.cursor/rules/*.mdc` for working ON launch-store.
 * - {@link renderContributorSkill} → the committed `.claude/skills/<id>/SKILL.md` for working ON launch-store.
 *
 * Consumer files carry a `generated by launch vX.Y.Z` stamp (they live in a user's repo, where the
 * version that wrote them is useful); the committed contributor files do not (git tracks their history).
 * Recipes invoke `npx launch …`, which resolves the locally-installed binary after the bootstrap install.
 */

import {
  BASE_CONTEXT,
  CONSUMER_SKILLS,
  CONTRIBUTOR_RULES,
  CONTRIBUTOR_SKILLS,
} from './registry.js';
import type {
  BaseContext,
  ConsumerSkill,
  ContributorRule,
  ContributorSkill,
  GeneratedAgentFile,
  SkillStep,
} from '../types.js';

/** The HTML-comment fences around the managed Launch section in a consumer's `AGENTS.md` / `CLAUDE.md`. */
export const MANAGED_START = '<!-- launch:start -->';

/** Closing fence for the managed Launch section; see {@link MANAGED_START}. */
export const MANAGED_END = '<!-- launch:end -->';

/** The version stamp line dropped into every consumer file so `launch agents check` can spot drift. */
function stamp(version: string): string {
  return `<!-- generated by launch v${version} · \`npx launch agents init\` · do not hand-edit -->`;
}

/** Render one recipe step as a code-spanned `npx launch …` line plus its note. */
function renderStep(step: SkillStep): string {
  const command = ['npx', 'launch', ...step.path, ...(step.args ?? [])].join(' ');
  return `\`${command}\` — ${step.note}`;
}

/** Render a skill's reference catalog as a two-column markdown table. */
function renderReferenceTable(commands: SkillStep[]): string {
  const rows = commands.map((step) => {
    const command = ['npx', 'launch', ...step.path, ...(step.args ?? [])].join(' ');
    return `| \`${command}\` | ${step.note} |`;
  });
  return ['| Command | What it does |', '| --- | --- |', ...rows].join('\n');
}

/** Render a bulleted "Use this when" list from a skill's triggers. */
function renderTriggers(triggers: string[]): string {
  return ['## Use this when', '', ...triggers.map((t) => `- ${t}`)].join('\n');
}

/** Render a skill's numbered recipe. */
function renderRecipe(steps: SkillStep[]): string {
  return ['## Steps', '', ...steps.map((step, i) => `${i + 1}. ${renderStep(step)}`)].join('\n');
}

/** Render a skill's cautions block, or `""` when it has none. */
function renderCautions(cautions: string[] | undefined): string {
  if (!cautions || cautions.length === 0) return '';
  return ['## Cautions', '', ...cautions.map((c) => `- ${c}`)].join('\n');
}

/** Join non-empty markdown chunks with blank lines, then end with a single trailing newline. */
function joinSections(sections: string[]): string {
  return `${sections.filter((s) => s.trim() !== '').join('\n\n')}\n`;
}

/**
 * Render the Claude Skill files for one skill: always a `SKILL.md`, plus a bundled `reference.md` when
 * the skill carries a {@link ConsumerSkill.reference} (large skills only — progressive disclosure). The
 * SKILL.md frontmatter is exactly `name` + `description`, Claude's two trigger fields.
 */
export function renderClaudeSkillFiles(
  skill: ConsumerSkill,
  version: string,
): GeneratedAgentFile[] {
  const frontmatter = ['---', `name: ${skill.id}`, `description: ${skill.description}`, '---'].join(
    '\n',
  );
  const referencePointer = skill.reference
    ? 'See [`reference.md`](./reference.md) for the full command surface across both stores.'
    : '';
  const body = joinSections([
    frontmatter,
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    referencePointer,
    renderCautions(skill.cautions),
  ]);
  const files: GeneratedAgentFile[] = [{ path: `.claude/skills/${skill.id}/SKILL.md`, body }];
  if (skill.reference) {
    const reference = joinSections([
      `# ${skill.title} — command reference`,
      stamp(version),
      skill.reference.intro,
      renderReferenceTable(skill.reference.commands),
    ]);
    files.push({ path: `.claude/skills/${skill.id}/reference.md`, body: reference });
  }
  return files;
}

/** Render the EAS → Launch command map as a markdown table. */
function renderCommandMap(base: BaseContext): string {
  const rows = base.commandMap.map((row) => `| \`${row.eas}\` | \`${row.launch}\` | ${row.note} |`);
  return ['| EAS | Launch | Notes |', '| --- | --- | --- |', ...rows].join('\n');
}

/** Render the always-on base context as a sequence of markdown sections (shared by Cursor + AGENTS.md). */
function renderBaseSections(base: BaseContext, headingLevel: number): string[] {
  const h = '#'.repeat(headingLevel);
  return [
    base.intro,
    `${h} EAS → Launch\n\n${renderCommandMap(base)}`,
    `${h} Safety rails\n\n${base.rails.map((r) => `- ${r}`).join('\n')}`,
    [
      `${h} What an agent may run vs must confirm`,
      '',
      '**Run freely (idempotent, reversible, or read-only):**',
      '',
      ...base.guardrail.free.map((f) => `- ${f}`),
      '',
      '**Confirm with a human first (irreversible / public-facing):**',
      '',
      ...base.guardrail.confirm.map((c) => `- ${c}`),
    ].join('\n'),
    `${h} Getting started\n\n${base.bootstrap.map((b) => `- ${b}`).join('\n')}`,
  ];
}

/**
 * Render the Cursor base rule (`.cursor/rules/launch.mdc`): `alwaysApply: true`, so Cursor always knows
 * this repo ships with Launch, how its commands map from EAS, and where the guardrails are.
 */
export function renderCursorBaseRule(
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile {
  const frontmatter = [
    '---',
    'description: Launch — build, sign & ship this app to the App Store / Play (always-on context)',
    'alwaysApply: true',
    '---',
  ].join('\n');
  const body = joinSections([
    frontmatter,
    '# Launch',
    stamp(version),
    ...renderBaseSections(base, 2),
  ]);
  return { path: '.cursor/rules/launch.mdc', body };
}

/**
 * Render one Cursor task rule (`.cursor/rules/launch-<id>.mdc`): description-driven (Agent-Requested),
 * so Cursor pulls it in when the developer's intent matches. Cursor has no progressive disclosure, so a
 * large skill's reference catalog is flattened inline rather than split into a separate file.
 */
export function renderCursorTaskRule(skill: ConsumerSkill, version: string): GeneratedAgentFile {
  const frontmatter = [
    '---',
    `description: ${skill.description}`,
    'alwaysApply: false',
    '---',
  ].join('\n');
  const reference = skill.reference
    ? `## Command reference\n\n${skill.reference.intro}\n\n${renderReferenceTable(skill.reference.commands)}`
    : '';
  const body = joinSections([
    frontmatter,
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    reference,
    renderCautions(skill.cautions),
  ]);
  return { path: `.cursor/rules/${skill.id}.mdc`, body };
}

/** Render one skill flattened into an `AGENTS.md` subsection (Codex has no skills — one file holds all). */
function renderSkillSection(skill: ConsumerSkill): string {
  const parts = [
    `### ${skill.title}`,
    `_Use when: ${skill.triggers.join('; ')}._`,
    skill.steps.map((step, i) => `${i + 1}. ${renderStep(step)}`).join('\n'),
    skill.body,
  ];
  if (skill.reference) {
    parts.push(
      `**Command reference.** ${skill.reference.intro}`,
      renderReferenceTable(skill.reference.commands),
    );
  }
  if (skill.cautions && skill.cautions.length > 0) {
    parts.push(`**Cautions:**\n${skill.cautions.map((c) => `- ${c}`).join('\n')}`);
  }
  return parts.filter((p) => p.trim() !== '').join('\n\n');
}

/**
 * Render the managed Launch section for a consumer's `AGENTS.md` — the always-on base context plus all
 * six task recipes flattened (Codex reads only this file, and a consumer's `CLAUDE.md` imports it). The
 * returned string INCLUDES the {@link MANAGED_START}/{@link MANAGED_END} fences so
 * {@link spliceManagedBlock} can swap the whole region without touching the user's own `AGENTS.md` prose.
 */
export function renderAgentsBlock(
  version: string,
  base: BaseContext = BASE_CONTEXT,
  skills: ConsumerSkill[] = CONSUMER_SKILLS,
): string {
  const sections = [
    '## Shipping this app with Launch',
    stamp(version),
    ...renderBaseSections(base, 3),
    '### Common tasks',
    skills.map(renderSkillSection).join('\n\n'),
  ];
  const inner = sections.filter((s) => s.trim() !== '').join('\n\n');
  return `${MANAGED_START}\n${inner}\n${MANAGED_END}`;
}

/**
 * Render the managed Launch section for a consumer's `CLAUDE.md`: import the shared `AGENTS.md` base and
 * point at the task Skills. Always-on context for Claude lives in `CLAUDE.md` (loaded every session); the
 * task detail lives in the description-triggered Skills under `.claude/skills/`. Includes the fences.
 */
export function renderClaudeMemoryBlock(
  version: string,
  skills: ConsumerSkill[] = CONSUMER_SKILLS,
): string {
  const skillList = skills.map((s) => `\`${s.id}\``).join(', ');
  const inner = [
    '## Launch',
    stamp(version),
    'This repo ships with **Launch** (build, sign & ship to the App Store / Play). The always-on context and the EAS → Launch map live in `AGENTS.md` — imported here:',
    '@AGENTS.md',
    `Task recipes are Claude Skills under \`.claude/skills/\` (${skillList}); reach for the one matching the request. Before any PUBLIC release (\`launch release\`), credential change, or applying a store reconcile to a live listing, confirm with the developer.`,
  ].join('\n\n');
  return `${MANAGED_START}\n${inner}\n${MANAGED_END}`;
}

/**
 * Splice a freshly rendered managed block (which already carries its fences) into an existing file,
 * replacing the previous {@link MANAGED_START}…{@link MANAGED_END} region. When the file has no fences
 * yet, the block is appended and the user's existing content is preserved above it; an empty/absent file
 * becomes just the block. This is what lets `launch agents init` co-exist with a user's own `AGENTS.md`.
 */
export function spliceManagedBlock(existing: string, blockWithMarkers: string): string {
  const start = existing.indexOf(MANAGED_START);
  const end = existing.indexOf(MANAGED_END);
  if (start !== -1 && end !== -1 && end > start) {
    return existing.slice(0, start) + blockWithMarkers + existing.slice(end + MANAGED_END.length);
  }
  if (existing.trim() === '') return `${blockWithMarkers}\n`;
  return `${existing.replace(/\n*$/, '')}\n\n${blockWithMarkers}\n`;
}

/**
 * Render one committed contributor rule (`.cursor/rules/<file>.mdc`) for working ON launch-store. No
 * version stamp — git tracks these; `globs` is emitted only for glob-scoped rules, and `alwaysApply` for
 * the base rule. `AGENTS.md` stays the canonical prose these point back to.
 */
export function renderContributorRule(rule: ContributorRule): GeneratedAgentFile {
  const frontmatter = ['---', `description: ${rule.description}`];
  if (rule.globs.length > 0) frontmatter.push(`globs: ${rule.globs.join(',')}`);
  frontmatter.push(`alwaysApply: ${rule.alwaysApply}`, '---');
  const body = `${frontmatter.join('\n')}\n\n${rule.body}\n`;
  return { path: `.cursor/rules/${rule.file}.mdc`, body };
}

/** Render every committed contributor rule — the list `npm run docs:gen` writes and `docs:check` gates. */
export function renderContributorRules(
  rules: ContributorRule[] = CONTRIBUTOR_RULES,
): GeneratedAgentFile[] {
  return rules.map(renderContributorRule);
}

/**
 * Render one committed contributor Claude skill (`.claude/skills/<id>/SKILL.md`) for working ON
 * launch-store. Like {@link renderContributorRule}, no version stamp — git tracks these. The steps are
 * free-form markdown (npm scripts, file edits), so they render as a plain numbered list rather than the
 * `npx launch …` lines a {@link ConsumerSkill} produces.
 */
export function renderContributorSkill(skill: ContributorSkill): GeneratedAgentFile {
  const frontmatter = ['---', `name: ${skill.id}`, `description: ${skill.description}`, '---'].join(
    '\n',
  );
  const recipe = ['## Steps', '', ...skill.steps.map((step, i) => `${i + 1}. ${step}`)].join('\n');
  const body = joinSections([
    frontmatter,
    `# ${skill.title}`,
    renderTriggers(skill.triggers),
    recipe,
    skill.body,
    renderCautions(skill.cautions),
  ]);
  return { path: `.claude/skills/${skill.id}/SKILL.md`, body };
}

/** Render every committed contributor skill — the list `npm run docs:gen` writes and `docs:check` gates. */
export function renderContributorSkills(
  skills: ContributorSkill[] = CONTRIBUTOR_SKILLS,
): GeneratedAgentFile[] {
  return skills.map(renderContributorSkill);
}
