import {
  BASE_CONTEXT,
  CONSUMER_SKILLS,
  CONTRIBUTOR_RULES,
  CONTRIBUTOR_SKILLS,
} from './registry.js';
import type {
  BaseContext,
  ConsumerSkill,
  ContributorRule,
  ContributorSkill,
  GeneratedAgentFile,
  SkillStep,
} from '../types/agents.js';
/** The HTML-comment fences around the managed Launch section in a consumer's `AGENTS.md` / `CLAUDE.md`. */
export const MANAGED_START = '<!-- launch:start -->';
/** Closing fence for the managed Launch section; see {@link MANAGED_START}. */
export const MANAGED_END = '<!-- launch:end -->';
/** The version stamp line dropped into every consumer file so `launch agents check` can spot drift. */
const stamp = (version: string): string => {
  return `<!-- generated by launch v${version} - \`npx launch agents init\` - do not hand-edit -->`;
};
/** Render one recipe step as a code-spanned `npx launch ...` line plus its note. */
const renderStep = (step: SkillStep): string => {
  const commandParts = ['npx', 'launch', ...step.path];
  if (step.args !== undefined) commandParts.push(...step.args);
  const command = commandParts.join(' ');
  return `\`${command}\` - ${step.note}`;
};
/** Render a skill's reference catalog as a two-column markdown table. */
const renderReferenceTable = (commands: readonly SkillStep[]): string => {
  const rows = commands.map((step) => {
    const commandParts = ['npx', 'launch', ...step.path];
    if (step.args !== undefined) commandParts.push(...step.args);
    const command = commandParts.join(' ');
    return `| \`${command}\` | ${step.note} |`;
  });
  return ['| Command | What it does |', '| --- | --- |', ...rows].join('\n');
};
/** Render a bulleted "Use this when" list from a skill's triggers. */
const renderTriggers = (triggers: readonly string[]): string => {
  return ['## Use this when', '', ...triggers.map((t) => `- ${t}`)].join('\n');
};
/** Render a skill's numbered recipe. */
const renderRecipe = (steps: readonly SkillStep[]): string => {
  return ['## Steps', '', ...steps.map((step, i) => `${i + 1}. ${renderStep(step)}`)].join('\n');
};
/** Render a skill's cautions block, or `""` when it has none. */
const renderCautions = (cautions: readonly string[] | undefined): string => {
  if (!cautions) return '';
  if (cautions.length === 0) return '';
  return ['## Cautions', '', ...cautions.map((c) => `- ${c}`)].join('\n');
};
/** Join non-empty markdown chunks with blank lines, then end with a single trailing newline. */
const joinSections = (sections: readonly string[]): string => {
  return `${sections.filter((s) => s.trim() !== '').join('\n\n')}\n`;
};
/**
 * Render the Claude Skill files for one skill: always a `SKILL.md`, plus a bundled `reference.md` when
 * the skill carries a {@link ConsumerSkill.reference} (large skills only - progressive disclosure). The
 * SKILL.md frontmatter is exactly `name` + `description`, Claude's two trigger fields.
 */
export const renderClaudeSkillFiles = (
  skill: ConsumerSkill,
  version: string,
): GeneratedAgentFile[] => {
  const frontmatter = ['---', `name: ${skill.id}`, `description: ${skill.description}`, '---'].join(
    '\n',
  );
  let referencePointer = '';
  if (skill.reference) {
    referencePointer =
      'See [`reference.md`](./reference.md) for the full command surface across both stores.';
  }
  const renderedMarkdown = joinSections([
    frontmatter,
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    referencePointer,
    renderCautions(skill.cautions),
  ]);
  const files: GeneratedAgentFile[] = [
    { path: `.claude/skills/${skill.id}/SKILL.md`, body: renderedMarkdown },
  ];
  if (skill.reference) {
    const reference = joinSections([
      `# ${skill.title} - command reference`,
      stamp(version),
      skill.reference.intro,
      renderReferenceTable(skill.reference.commands),
    ]);
    files.push({ path: `.claude/skills/${skill.id}/reference.md`, body: reference });
  }
  return files;
};
/** Render the EAS -> Launch command map as a markdown table. */
const renderCommandMap = (base: BaseContext): string => {
  const commandMappings = base.commandMap.map(
    (commandMapping) =>
      `| \`${commandMapping.eas}\` | \`${commandMapping.launch}\` | ${commandMapping.note} |`,
  );
  return ['| EAS | Launch | Notes |', '| --- | --- | --- |', ...commandMappings].join('\n');
};
/** Render the always-on base context as a sequence of markdown sections (shared by Cursor + AGENTS.md). */
const renderBaseSections = (base: BaseContext, headingLevel: number): string[] => {
  const h = '#'.repeat(headingLevel);
  return [
    base.intro,
    `${h} EAS -> Launch\n\n${renderCommandMap(base)}`,
    `${h} Safety rails\n\n${base.rails.map((r) => `- ${r}`).join('\n')}`,
    [
      `${h} What an agent may run vs must confirm`,
      '',
      '**Run freely (idempotent, reversible, or read-only):**',
      '',
      ...base.guardrail.free.map((f) => `- ${f}`),
      '',
      '**Confirm with a human first (irreversible / public-facing):**',
      '',
      ...base.guardrail.confirm.map((c) => `- ${c}`),
    ].join('\n'),
    `${h} Getting started\n\n${base.bootstrap.map((b) => `- ${b}`).join('\n')}`,
  ];
};
/**
 * Render the Cursor base rule (`.cursor/rules/launch.mdc`): `alwaysApply: true`, so Cursor always knows
 * this repo ships with Launch, how its commands map from EAS, and where the guardrails are.
 */
export const renderCursorBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => {
  const frontmatter = [
    '---',
    'description: Launch - build, sign & ship this app to the App Store / Play (always-on context)',
    'alwaysApply: true',
    '---',
  ].join('\n');
  const renderedMarkdown = joinSections([
    frontmatter,
    '# Launch',
    stamp(version),
    ...renderBaseSections(base, 2),
  ]);
  return { path: '.cursor/rules/launch.mdc', body: renderedMarkdown };
};
/**
 * Render one Cursor task rule (`.cursor/rules/launch-<id>.mdc`): description-driven (Agent-Requested),
 * so Cursor pulls it in when the developer's intent matches. Cursor has no progressive disclosure, so a
 * large skill's reference catalog is flattened inline rather than split into a separate file.
 */
export const renderCursorTaskRule = (skill: ConsumerSkill, version: string): GeneratedAgentFile => {
  const frontmatter = [
    '---',
    `description: ${skill.description}`,
    'alwaysApply: false',
    '---',
  ].join('\n');
  let reference = '';
  if (skill.reference) {
    reference = `## Command reference\n\n${skill.reference.intro}\n\n${renderReferenceTable(skill.reference.commands)}`;
  }
  const renderedMarkdown = joinSections([
    frontmatter,
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    reference,
    renderCautions(skill.cautions),
  ]);
  return { path: `.cursor/rules/${skill.id}.mdc`, body: renderedMarkdown };
};
/** Render one skill flattened into an `AGENTS.md` subsection (Codex has no skills - one file holds all). */
const renderSkillSection = (skill: ConsumerSkill): string => {
  const parts = [
    `### ${skill.title}`,
    `_Use when: ${skill.triggers.join('; ')}._`,
    skill.steps.map((step, i) => `${i + 1}. ${renderStep(step)}`).join('\n'),
    skill.body,
  ];
  if (skill.reference) {
    parts.push(
      `**Command reference.** ${skill.reference.intro}`,
      renderReferenceTable(skill.reference.commands),
    );
  }
  if (skill.cautions && skill.cautions.length > 0) {
    parts.push(`**Cautions:**\n${skill.cautions.map((c) => `- ${c}`).join('\n')}`);
  }
  return parts.filter((p) => p.trim() !== '').join('\n\n');
};
/**
 * Render the managed Launch section for a consumer's `AGENTS.md` - the always-on base context plus all
 * six task recipes flattened (Codex reads only this file, and a consumer's `CLAUDE.md` imports it). The
 * returned string INCLUDES the {@link MANAGED_START}/{@link MANAGED_END} fences so
 * {@link spliceManagedBlock} can swap the whole region without touching the user's own `AGENTS.md` prose.
 */
export const renderAgentsBlock = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): string => {
  const sections = [
    '## Shipping this app with Launch',
    stamp(version),
    ...renderBaseSections(base, 3),
    '### Common tasks',
    skills.map(renderSkillSection).join('\n\n'),
  ];
  const inner = sections.filter((s) => s.trim() !== '').join('\n\n');
  return `${MANAGED_START}\n${inner}\n${MANAGED_END}`;
};
/**
 * Render the managed Launch section for a consumer's `CLAUDE.md`: import the shared `AGENTS.md` base and
 * point at the task Skills. Always-on context for Claude lives in `CLAUDE.md` (loaded every session); the
 * task detail lives in the description-triggered Skills under `.claude/skills/`. Includes the fences.
 */
export const renderClaudeMemoryBlock = (
  version: string,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): string => {
  const skillList = skills.map((s) => `\`${s.id}\``).join(', ');
  const inner = [
    '## Launch',
    stamp(version),
    'This repo ships with **Launch** (build, sign & ship to the App Store / Play). The always-on context and the EAS -> Launch map live in `AGENTS.md` - imported here:',
    '@AGENTS.md',
    `Task recipes are Claude Skills under \`.claude/skills/\` (${skillList}); reach for the one matching the request. Before any PUBLIC release (\`launch release\`), credential change, or applying a store reconcile to a live listing, confirm with the developer.`,
  ].join('\n\n');
  return `${MANAGED_START}\n${inner}\n${MANAGED_END}`;
};
/**
 * Splice a freshly rendered managed block (which already carries its fences) into an existing file,
 * replacing the previous {@link MANAGED_START}...{@link MANAGED_END} region. When the file has no fences
 * yet, the block is appended and the user's existing content is preserved above it; an empty/absent file
 * becomes just the block. This is what lets `launch agents init` co-exist with a user's own `AGENTS.md`.
 */
export const spliceManagedBlock = (existing: string, blockWithMarkers: string): string => {
  const start = existing.indexOf(MANAGED_START);
  const end = existing.indexOf(MANAGED_END);
  if (start !== -1 && end !== -1 && end > start) {
    return existing.slice(0, start) + blockWithMarkers + existing.slice(end + MANAGED_END.length);
  }
  if (existing.trim() === '') return `${blockWithMarkers}\n`;
  return `${existing.replace(/\n*$/, '')}\n\n${blockWithMarkers}\n`;
};
/**
 * Render one committed contributor rule (`.cursor/rules/<file>.mdc`) for working ON launch-store. No
 * version stamp - git tracks these; `globs` is emitted only for glob-scoped rules, and `alwaysApply` for
 * the base rule. `AGENTS.md` stays the canonical prose these point back to.
 */
export const renderContributorRule = (rule: ContributorRule): GeneratedAgentFile => {
  const frontmatter = ['---', `description: ${rule.description}`];
  if (rule.globs.length > 0) frontmatter.push(`globs: ${rule.globs.join(',')}`);
  frontmatter.push(`alwaysApply: ${rule.alwaysApply}`, '---');
  const renderedMarkdown = `${frontmatter.join('\n')}\n\n${rule.body}\n`;
  return { path: `.cursor/rules/${rule.file}.mdc`, body: renderedMarkdown };
};
/** Render every committed contributor rule - the list `pnpm docs:gen` writes and `docs:check` gates. */
export const renderContributorRules = (
  rules: ContributorRule[] = CONTRIBUTOR_RULES,
): GeneratedAgentFile[] => {
  return rules.map(renderContributorRule);
};
/**
 * Render one committed contributor Claude skill (`.claude/skills/<id>/SKILL.md`) for working ON
 * launch-store. Like {@link renderContributorRule}, no version stamp - git tracks these. The steps are
 * free-form markdown (npm scripts, file edits), so they render as a plain numbered list rather than the
 * `npx launch ...` lines a {@link ConsumerSkill} produces.
 */
export const renderContributorSkill = (skill: ContributorSkill): GeneratedAgentFile => {
  const frontmatter = ['---', `name: ${skill.id}`, `description: ${skill.description}`, '---'].join(
    '\n',
  );
  const recipe = ['## Steps', '', ...skill.steps.map((step, i) => `${i + 1}. ${step}`)].join('\n');
  const renderedMarkdown = joinSections([
    frontmatter,
    `# ${skill.title}`,
    renderTriggers(skill.triggers),
    recipe,
    skill.body,
    renderCautions(skill.cautions),
  ]);
  return { path: `.claude/skills/${skill.id}/SKILL.md`, body: renderedMarkdown };
};
/** Render every committed contributor skill - the list `pnpm docs:gen` writes and `docs:check` gates. */
export const renderContributorSkills = (
  skills: ContributorSkill[] = CONTRIBUTOR_SKILLS,
): GeneratedAgentFile[] => {
  return skills.map(renderContributorSkill);
};
//  Windsurf (.windsurf/rules/*.md)
/**
 * Render the Windsurf base rule (`.windsurf/rules/launch.md`): `trigger: always`, so Windsurf always
 * knows this repo ships with Launch. Format uses YAML frontmatter with `trigger` field.
 */
export const renderWindsurfBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => {
  const frontmatter = ['---', 'trigger: always', '---'].join('\n');
  const renderedMarkdown = joinSections([
    frontmatter,
    '# Launch',
    stamp(version),
    ...renderBaseSections(base, 2),
  ]);
  return { path: '.windsurf/rules/launch.md', body: renderedMarkdown };
};
/**
 * Render one Windsurf task rule (`.windsurf/rules/launch-<id>.md`): `trigger: auto` with a catch-all
 * glob, so Windsurf pulls it in when the developer's intent matches. Large skills have their reference
 * catalog flattened inline.
 */
export const renderWindsurfTaskRule = (
  skill: ConsumerSkill,
  version: string,
): GeneratedAgentFile => {
  const frontmatter = ['---', 'trigger: auto', 'globs: "**/*"', '---'].join('\n');
  let reference = '';
  if (skill.reference) {
    reference = `## Command reference\n\n${skill.reference.intro}\n\n${renderReferenceTable(skill.reference.commands)}`;
  }
  const renderedMarkdown = joinSections([
    frontmatter,
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    reference,
    renderCautions(skill.cautions),
  ]);
  return { path: `.windsurf/rules/${skill.id}.md`, body: renderedMarkdown };
};
//  Copilot (.github/copilot-instructions.md)
/**
 * Render the managed Launch block for a consumer's `.github/copilot-instructions.md`. Copilot uses a
 * single file, so the Launch context (base + condensed skills overview) is emitted as a spliced managed
 * block - the same pattern as `AGENTS.md` - to preserve any user content around it.
 */
export const renderCopilotBlock = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): string => {
  const skillSummaries = skills.map((s) => `- **${s.title}**: ${s.description}`).join('\n');
  const sections = [
    '## Shipping this app with Launch',
    stamp(version),
    ...renderBaseSections(base, 3),
    '### Available workflows',
    skillSummaries,
    ...skills.map(renderSkillSection),
  ];
  const inner = sections.filter((s) => s.trim() !== '').join('\n\n');
  return `${MANAGED_START}\n${inner}\n${MANAGED_END}`;
};
//  Kiro (.kiro/steering/launch.md)
/**
 * Render the Kiro steering hook (`.kiro/steering/launch.md`): a single file that provides all Launch
 * context. Kiro steering hooks are plain markdown that fire on events - this one contains the base
 * context plus all task workflows so Kiro has the full picture in one file.
 */
export const renderKiroSteering = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): GeneratedAgentFile => {
  const renderedMarkdown = joinSections([
    '# Launch - build, sign & ship to the App Store / Play',
    stamp(version),
    ...renderBaseSections(base, 2),
    '## Common tasks',
    skills.map(renderSkillSection).join('\n\n'),
  ]);
  return { path: '.kiro/steering/launch.md', body: renderedMarkdown };
};
//  Cline (.cline/rules/*.md)
/**
 * Render the Cline base rule (`.cline/rules/launch.md`): plain markdown (no frontmatter), always
 * loaded by Cline. Contains the base context so Cline always knows Launch is present.
 */
export const renderClineBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => {
  const renderedMarkdown = joinSections([
    '# Launch',
    stamp(version),
    ...renderBaseSections(base, 2),
  ]);
  return { path: '.cline/rules/launch.md', body: renderedMarkdown };
};
/**
 * Render one Cline task rule (`.cline/rules/launch-<id>.md`): plain markdown, auto-loaded by Cline
 * when files in the `.cline/rules/` directory are present. Large skills have their reference catalog
 * flattened inline.
 */
export const renderClineTaskRule = (skill: ConsumerSkill, version: string): GeneratedAgentFile => {
  let reference = '';
  if (skill.reference) {
    reference = `## Command reference\n\n${skill.reference.intro}\n\n${renderReferenceTable(skill.reference.commands)}`;
  }
  const renderedMarkdown = joinSections([
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    reference,
    renderCautions(skill.cautions),
  ]);
  return { path: `.cline/rules/${skill.id}.md`, body: renderedMarkdown };
};
//  Amazon Q (.amazonq/rules/*.md)
/**
 * Render the Amazon Q base rule (`.amazonq/rules/launch.md`): plain markdown, auto-loaded. Contains
 * the base context so Amazon Q always knows Launch is present.
 */
export const renderAmazonQBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => {
  const renderedMarkdown = joinSections([
    '# Launch',
    stamp(version),
    ...renderBaseSections(base, 2),
  ]);
  return { path: '.amazonq/rules/launch.md', body: renderedMarkdown };
};
/**
 * Render one Amazon Q task rule (`.amazonq/rules/launch-<id>.md`): plain markdown, auto-loaded.
 * Large skills have their reference catalog flattened inline.
 */
export const renderAmazonQTaskRule = (
  skill: ConsumerSkill,
  version: string,
): GeneratedAgentFile => {
  let reference = '';
  if (skill.reference) {
    reference = `## Command reference\n\n${skill.reference.intro}\n\n${renderReferenceTable(skill.reference.commands)}`;
  }
  const renderedMarkdown = joinSections([
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    reference,
    renderCautions(skill.cautions),
  ]);
  return { path: `.amazonq/rules/${skill.id}.md`, body: renderedMarkdown };
};
