import { describe, expect, it } from "vitest";
import { CONSUMER_SKILLS, CONTRIBUTOR_RULES, CONTRIBUTOR_SKILLS } from "./registry.js";
import {
  MANAGED_END,
  MANAGED_START,
  renderAgentsBlock,
  renderClaudeMemoryBlock,
  renderClaudeSkillFiles,
  renderContributorRule,
  renderContributorSkill,
  renderCursorBaseRule,
  renderCursorTaskRule,
  spliceManagedBlock,
} from "./render.js";

const skill = (id: string) => CONSUMER_SKILLS.find((s) => s.id === id)!;
const VERSION = "9.9.9";

describe("Claude skill rendering", () => {
  it("emits a single SKILL.md with name+description frontmatter and a version stamp for a small skill", () => {
    const files = renderClaudeSkillFiles(skill("launch-ship"), VERSION);
    expect(files.map((f) => f.path)).toEqual([".claude/skills/launch-ship/SKILL.md"]);
    const body = files[0]!.body;
    expect(body.startsWith("---\nname: launch-ship\ndescription: ")).toBe(true);
    expect(body).toContain(`generated by launch v${VERSION}`);
    expect(body).toContain("`npx launch init`");
    expect(body).not.toContain("reference.md");
  });

  it("bundles a reference.md for the large store-config skill and points the SKILL.md at it", () => {
    const files = renderClaudeSkillFiles(skill("launch-store-config"), VERSION);
    expect(files.map((f) => f.path)).toEqual([
      ".claude/skills/launch-store-config/SKILL.md",
      ".claude/skills/launch-store-config/reference.md",
    ]);
    expect(files[0]!.body).toContain("reference.md");
    expect(files[1]!.body).toContain("| Command | What it does |");
  });
});

describe("Cursor rule rendering", () => {
  it("makes the base rule always-on and includes the EAS map and the release guardrail", () => {
    const rule = renderCursorBaseRule(VERSION);
    expect(rule.path).toBe(".cursor/rules/launch.mdc");
    expect(rule.body).toContain("alwaysApply: true");
    expect(rule.body).toContain("EAS → Launch");
    expect(rule.body).toContain("launch release");
  });

  it("makes each task rule description-driven (Agent-Requested), not always-on", () => {
    const rule = renderCursorTaskRule(skill("launch-release"), VERSION);
    expect(rule.path).toBe(".cursor/rules/launch-release.mdc");
    expect(rule.body).toContain("alwaysApply: false");
    expect(rule.body).toContain("description: ");
    expect(rule.body).toContain("`npx launch release ios`");
  });
});

describe("AGENTS.md and CLAUDE.md managed blocks", () => {
  it("wraps the AGENTS.md block in fences and flattens every task for Codex", () => {
    const block = renderAgentsBlock(VERSION);
    expect(block.startsWith(MANAGED_START)).toBe(true);
    expect(block.endsWith(MANAGED_END)).toBe(true);
    for (const s of CONSUMER_SKILLS) expect(block, `missing ${s.id}`).toContain(s.title);
    expect(block).toContain("| Command | What it does |"); // store-config reference flattened inline
  });

  it("imports AGENTS.md and lists the skills in the CLAUDE.md block", () => {
    const block = renderClaudeMemoryBlock(VERSION);
    expect(block).toContain("@AGENTS.md");
    expect(block).toContain("`launch-ship`");
    expect(block.startsWith(MANAGED_START)).toBe(true);
  });
});

describe("spliceManagedBlock preserves the user's own content", () => {
  const block = `${MANAGED_START}\nNEW\n${MANAGED_END}`;

  it("returns just the block for an empty file", () => {
    expect(spliceManagedBlock("", block)).toBe(`${block}\n`);
  });

  it("appends below existing content when there are no fences yet", () => {
    const result = spliceManagedBlock("# My app\n\nmy own rules\n", block);
    expect(result).toContain("# My app");
    expect(result).toContain("my own rules");
    expect(result).toContain("NEW");
  });

  it("replaces only the fenced region, keeping text around it", () => {
    const existing = `# My app\n\n${MANAGED_START}\nOLD\n${MANAGED_END}\n\nfooter\n`;
    const result = spliceManagedBlock(existing, block);
    expect(result).toContain("# My app");
    expect(result).toContain("footer");
    expect(result).toContain("NEW");
    expect(result).not.toContain("OLD");
  });
});

describe("contributor rules are committed without a version stamp", () => {
  it("renders the base rule as always-on with no generated-by stamp", () => {
    const file = renderContributorRule(CONTRIBUTOR_RULES[0]!);
    expect(file.path).toBe(".cursor/rules/launch.mdc");
    expect(file.body).toContain("alwaysApply: true");
    expect(file.body).not.toContain("generated by launch");
    expect(file.body).toContain("AGENTS.md");
  });

  it("emits the glob line for a path-scoped rule", () => {
    const providers = CONTRIBUTOR_RULES.find((r) => r.file === "providers")!;
    const file = renderContributorRule(providers);
    expect(file.body).toContain("globs: src/providers/**");
    expect(file.body).toContain("alwaysApply: false");
  });
});

describe("contributor Claude skills are committed without a version stamp", () => {
  const gate = CONTRIBUTOR_SKILLS.find((s) => s.id === "run-the-gate")!;

  it("renders a SKILL.md with name+description frontmatter, the recipe, and no generated-by stamp", () => {
    const file = renderContributorSkill(gate);
    expect(file.path).toBe(".claude/skills/run-the-gate/SKILL.md");
    expect(file.body.startsWith("---\nname: run-the-gate\ndescription: ")).toBe(true);
    expect(file.body).not.toContain("generated by launch");
    expect(file.body).toContain("## Use this when");
    expect(file.body).toContain("## Steps");
    expect(file.body).toContain("npm run docs:check");
    expect(file.body).toContain("(../../../AGENTS.md)");
  });

  it("renders the skill-specific cautions block when a skill has cautions", () => {
    const provider = CONTRIBUTOR_SKILLS.find((s) => s.id === "add-a-provider")!;
    expect(renderContributorSkill(provider).body).toContain("## Cautions");
  });
});
