import {
  BASE_CONTEXT,
  CONSUMER_SKILLS,
  CONTRIBUTOR_RULES,
  CONTRIBUTOR_SKILLS,
} from './registry.js';
import type {
  BaseContext,
  ConsumerSkill,
  ContributorRule,
  ContributorSkill,
  GeneratedAgentFile,
  SkillStep,
} from '../types/agents.js';

/** HTML-comment fences around the managed Launch section in shared consumer docs. */
export const MANAGED_START = '<!-- launch:start -->';
/** Closing fence for the managed Launch section; see {@link MANAGED_START}. */
export const MANAGED_END = '<!-- launch:end -->';

/** Version stamp so `launch agents check` can detect drift without reading git. */
const stamp = (version: string): string =>
  `<!-- generated by launch v${version} - \`npx launch agents init\` - do not hand-edit -->`;

/** Render one recipe step as a code-spanned `npx launch ...` line plus its note. */
const renderStep = (step: SkillStep): string => {
  const commandParts = ['npx', 'launch', ...step.path];
  if (step.args !== undefined) commandParts.push(...step.args);
  return `\`${commandParts.join(' ')}\` - ${step.note}`;
};

/** Render a skill's reference catalog as a two-column markdown table. */
const renderReferenceTable = (commands: readonly SkillStep[]): string => {
  const rows = commands.map((step) => {
    const commandParts = ['npx', 'launch', ...step.path];
    if (step.args !== undefined) commandParts.push(...step.args);
    return `| \`${commandParts.join(' ')}\` | ${step.note} |`;
  });
  return ['| Command | What it does |', '| --- | --- |', ...rows].join('\n');
};

/** Inline command-reference section for targets without progressive disclosure files. */
const renderInlineReference = (skill: ConsumerSkill): string => {
  if (skill.reference === undefined) return '';
  return `## Command reference\n\n${skill.reference.intro}\n\n${renderReferenceTable(skill.reference.commands)}`;
};

/** Bulleted "Use this when" list from a skill's triggers. */
const renderTriggers = (triggers: readonly string[]): string =>
  ['## Use this when', '', ...triggers.map((trigger) => `- ${trigger}`)].join('\n');

/** Numbered recipe for consumer skills (`npx launch ...` lines). */
const renderRecipe = (steps: readonly SkillStep[]): string =>
  ['## Steps', '', ...steps.map((step, stepIndex) => `${stepIndex + 1}. ${renderStep(step)}`)].join(
    '\n',
  );

/** Cautions block, or empty when the skill has none. */
const renderCautions = (cautions: readonly string[] | undefined): string => {
  if (cautions === undefined) return '';
  if (cautions.length === 0) return '';
  return ['## Cautions', '', ...cautions.map((caution) => `- ${caution}`)].join('\n');
};

/** Join non-empty markdown chunks with blank lines, then end with a single trailing newline. */
const joinSections = (sections: readonly string[]): string =>
  `${sections.filter((section) => section.trim() !== '').join('\n\n')}\n`;

/** Wrap managed prose in the Launch start/end fences used by splice. */
const wrapManagedBlock = (sections: readonly string[]): string => {
  const inner = sections.filter((section) => section.trim() !== '').join('\n\n');
  return `${MANAGED_START}\n${inner}\n${MANAGED_END}`;
};

/** EAS -> Launch command map as a markdown table. */
const renderCommandMap = (base: BaseContext): string => {
  const commandMappings = base.commandMap.map(
    (commandMapping) =>
      `| \`${commandMapping.eas}\` | \`${commandMapping.launch}\` | ${commandMapping.note} |`,
  );
  return ['| EAS | Launch | Notes |', '| --- | --- | --- |', ...commandMappings].join('\n');
};

/** Always-on base context sections (shared by Cursor base rules and AGENTS.md). */
const renderBaseSections = (base: BaseContext, headingLevel: number): string[] => {
  const heading = '#'.repeat(headingLevel);
  return [
    base.intro,
    `${heading} EAS -> Launch\n\n${renderCommandMap(base)}`,
    `${heading} Safety rails\n\n${base.rails.map((rail) => `- ${rail}`).join('\n')}`,
    [
      `${heading} What an agent may run vs must confirm`,
      '',
      '**Run freely (idempotent, reversible, or read-only):**',
      '',
      ...base.guardrail.free.map((freeCommand) => `- ${freeCommand}`),
      '',
      '**Confirm with a human first (irreversible / public-facing):**',
      '',
      ...base.guardrail.confirm.map((confirmCommand) => `- ${confirmCommand}`),
    ].join('\n'),
    `${heading} Getting started\n\n${base.bootstrap.map((bootstrapLine) => `- ${bootstrapLine}`).join('\n')}`,
  ];
};

/** Shared body for description-driven task rules across Cursor/Windsurf/Cline/Amazon Q. */
const renderTaskSkillMarkdown = (
  skill: ConsumerSkill,
  version: string,
  leadingSections: readonly string[] = [],
): string =>
  joinSections([
    ...leadingSections,
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    renderInlineReference(skill),
    renderCautions(skill.cautions),
  ]);

/** Shared always-on base rule (optional frontmatter + Launch base sections). */
const renderBaseRuleMarkdown = (
  version: string,
  base: BaseContext,
  headingLevel: number,
  frontmatter: string | undefined,
): string => {
  const sections: string[] = [];
  if (frontmatter !== undefined) sections.push(frontmatter);
  sections.push('# Launch', stamp(version), ...renderBaseSections(base, headingLevel));
  return joinSections(sections);
};

/**
 * Claude Skill files for one skill: always `SKILL.md`, plus `reference.md` when the skill carries a
 * large catalog (progressive disclosure). Frontmatter is exactly Claude's two trigger fields.
 */
export const renderClaudeSkillFiles = (
  skill: ConsumerSkill,
  version: string,
): GeneratedAgentFile[] => {
  const frontmatter = ['---', `name: ${skill.id}`, `description: ${skill.description}`, '---'].join(
    '\n',
  );
  let referencePointer = '';
  if (skill.reference !== undefined) {
    referencePointer =
      'See [`reference.md`](./reference.md) for the full command surface across both stores.';
  }
  const skillMarkdown = joinSections([
    frontmatter,
    `# ${skill.title}`,
    stamp(version),
    renderTriggers(skill.triggers),
    renderRecipe(skill.steps),
    skill.body,
    referencePointer,
    renderCautions(skill.cautions),
  ]);
  const generatedFiles: GeneratedAgentFile[] = [
    { path: `.claude/skills/${skill.id}/SKILL.md`, body: skillMarkdown },
  ];
  if (skill.reference !== undefined) {
    const referenceMarkdown = joinSections([
      `# ${skill.title} - command reference`,
      stamp(version),
      skill.reference.intro,
      renderReferenceTable(skill.reference.commands),
    ]);
    generatedFiles.push({
      path: `.claude/skills/${skill.id}/reference.md`,
      body: referenceMarkdown,
    });
  }
  return generatedFiles;
};

/** Cursor base rule: `alwaysApply: true` so Cursor always knows Launch is present. */
export const renderCursorBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => {
  const frontmatter = [
    '---',
    'description: Launch - build, sign & ship this app to the App Store / Play (always-on context)',
    'alwaysApply: true',
    '---',
  ].join('\n');
  return {
    path: '.cursor/rules/launch.mdc',
    body: renderBaseRuleMarkdown(version, base, 2, frontmatter),
  };
};

/**
 * Cursor task rule: description-driven (Agent-Requested). Large skill references are flattened
 * inline - Cursor has no progressive disclosure files.
 */
export const renderCursorTaskRule = (skill: ConsumerSkill, version: string): GeneratedAgentFile => {
  const frontmatter = [
    '---',
    `description: ${skill.description}`,
    'alwaysApply: false',
    '---',
  ].join('\n');
  return {
    path: `.cursor/rules/${skill.id}.mdc`,
    body: renderTaskSkillMarkdown(skill, version, [frontmatter]),
  };
};

/** One skill flattened into an AGENTS.md subsection (Codex has no per-task skill files). */
const renderSkillSection = (skill: ConsumerSkill): string => {
  const parts = [
    `### ${skill.title}`,
    `_Use when: ${skill.triggers.join('; ')}._`,
    skill.steps.map((step, stepIndex) => `${stepIndex + 1}. ${renderStep(step)}`).join('\n'),
    skill.body,
  ];
  if (skill.reference !== undefined) {
    parts.push(
      `**Command reference.** ${skill.reference.intro}`,
      renderReferenceTable(skill.reference.commands),
    );
  }
  if (skill.cautions !== undefined && skill.cautions.length > 0) {
    parts.push(`**Cautions:**\n${skill.cautions.map((caution) => `- ${caution}`).join('\n')}`);
  }
  return parts.filter((part) => part.trim() !== '').join('\n\n');
};

/**
 * Managed Launch section for consumer `AGENTS.md` - base context plus every task recipe flattened.
 * Includes fences so {@link spliceManagedBlock} can replace the region without touching user prose.
 */
export const renderAgentsBlock = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): string =>
  wrapManagedBlock([
    '## Shipping this app with Launch',
    stamp(version),
    ...renderBaseSections(base, 3),
    '### Common tasks',
    skills.map(renderSkillSection).join('\n\n'),
  ]);

/**
 * Managed Launch section for consumer `CLAUDE.md`: import shared `AGENTS.md` and point at Skills.
 * Always-on context lives here; task detail lives under `.claude/skills/`.
 */
export const renderClaudeMemoryBlock = (
  version: string,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): string => {
  const skillList = skills.map((skill) => `\`${skill.id}\``).join(', ');
  return wrapManagedBlock([
    '## Launch',
    stamp(version),
    'This repo ships with **Launch** (build, sign & ship to the App Store / Play). The always-on context and the EAS -> Launch map live in `AGENTS.md` - imported here:',
    '@AGENTS.md',
    `Task recipes are Claude Skills under \`.claude/skills/\` (${skillList}); reach for the one matching the request. Before any PUBLIC release (\`launch release\`), credential change, or applying a store reconcile to a live listing, confirm with the developer.`,
  ]);
};

/**
 * Splice a fenced managed block into an existing file, replacing a prior Launch region when present.
 * Empty files become just the block; unfenced content is preserved above an appended block.
 */
export const spliceManagedBlock = (existing: string, blockWithMarkers: string): string => {
  const start = existing.indexOf(MANAGED_START);
  const end = existing.indexOf(MANAGED_END);
  if (start !== -1 && end !== -1 && end > start) {
    return existing.slice(0, start) + blockWithMarkers + existing.slice(end + MANAGED_END.length);
  }
  if (existing.trim() === '') return `${blockWithMarkers}\n`;
  return `${existing.replace(/\n*$/, '')}\n\n${blockWithMarkers}\n`;
};

/** One committed contributor Cursor rule for working ON launch-store (no version stamp - git tracks it). */
export const renderContributorRule = (rule: ContributorRule): GeneratedAgentFile => {
  const frontmatter = ['---', `description: ${rule.description}`];
  if (rule.globs.length > 0) frontmatter.push(`globs: ${rule.globs.join(',')}`);
  frontmatter.push(`alwaysApply: ${rule.alwaysApply}`, '---');
  return {
    path: `.cursor/rules/${rule.file}.mdc`,
    body: `${frontmatter.join('\n')}\n\n${rule.body}\n`,
  };
};

/** Every committed contributor rule (`pnpm docs:gen` / `docs:check`). */
export const renderContributorRules = (
  rules: readonly ContributorRule[] = CONTRIBUTOR_RULES,
): GeneratedAgentFile[] => rules.map(renderContributorRule);

/**
 * One committed contributor Claude skill. Steps are free-form markdown (repo workflow), not
 * `npx launch ...` lines.
 */
export const renderContributorSkill = (skill: ContributorSkill): GeneratedAgentFile => {
  const frontmatter = ['---', `name: ${skill.id}`, `description: ${skill.description}`, '---'].join(
    '\n',
  );
  const recipe = [
    '## Steps',
    '',
    ...skill.steps.map((step, stepIndex) => `${stepIndex + 1}. ${step}`),
  ].join('\n');
  return {
    path: `.claude/skills/${skill.id}/SKILL.md`,
    body: joinSections([
      frontmatter,
      `# ${skill.title}`,
      renderTriggers(skill.triggers),
      recipe,
      skill.body,
      renderCautions(skill.cautions),
    ]),
  };
};

/** Every committed contributor skill (`pnpm docs:gen` / `docs:check`). */
export const renderContributorSkills = (
  skills: readonly ContributorSkill[] = CONTRIBUTOR_SKILLS,
): GeneratedAgentFile[] => skills.map(renderContributorSkill);

/** Windsurf base rule: `trigger: always`. */
export const renderWindsurfBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => {
  const frontmatter = ['---', 'trigger: always', '---'].join('\n');
  return {
    path: '.windsurf/rules/launch.md',
    body: renderBaseRuleMarkdown(version, base, 2, frontmatter),
  };
};

/** Windsurf task rule: `trigger: auto` with a catch-all glob; references flattened inline. */
export const renderWindsurfTaskRule = (
  skill: ConsumerSkill,
  version: string,
): GeneratedAgentFile => {
  const frontmatter = ['---', 'trigger: auto', 'globs: "**/*"', '---'].join('\n');
  return {
    path: `.windsurf/rules/${skill.id}.md`,
    body: renderTaskSkillMarkdown(skill, version, [frontmatter]),
  };
};

/**
 * Managed Launch block for `.github/copilot-instructions.md` - base + condensed workflows,
 * fenced so user content around it is preserved.
 */
export const renderCopilotBlock = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): string => {
  const skillSummaries = skills
    .map((skill) => `- **${skill.title}**: ${skill.description}`)
    .join('\n');
  return wrapManagedBlock([
    '## Shipping this app with Launch',
    stamp(version),
    ...renderBaseSections(base, 3),
    '### Available workflows',
    skillSummaries,
    ...skills.map(renderSkillSection),
  ]);
};

/** Kiro steering hook: single plain-markdown file with base context plus every task. */
export const renderKiroSteering = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
  skills: readonly ConsumerSkill[] = CONSUMER_SKILLS,
): GeneratedAgentFile => ({
  path: '.kiro/steering/launch.md',
  body: joinSections([
    '# Launch - build, sign & ship to the App Store / Play',
    stamp(version),
    ...renderBaseSections(base, 2),
    '## Common tasks',
    skills.map(renderSkillSection).join('\n\n'),
  ]),
});

/** Cline base rule: plain markdown, always loaded. */
export const renderClineBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => ({
  path: '.cline/rules/launch.md',
  body: renderBaseRuleMarkdown(version, base, 2, undefined),
});

/** Cline task rule: plain markdown; references flattened inline. */
export const renderClineTaskRule = (skill: ConsumerSkill, version: string): GeneratedAgentFile => ({
  path: `.cline/rules/${skill.id}.md`,
  body: renderTaskSkillMarkdown(skill, version),
});

/** Amazon Q base rule: plain markdown, auto-loaded. */
export const renderAmazonQBaseRule = (
  version: string,
  base: BaseContext = BASE_CONTEXT,
): GeneratedAgentFile => ({
  path: '.amazonq/rules/launch.md',
  body: renderBaseRuleMarkdown(version, base, 2, undefined),
});

/** Amazon Q task rule: plain markdown; references flattened inline. */
export const renderAmazonQTaskRule = (
  skill: ConsumerSkill,
  version: string,
): GeneratedAgentFile => ({
  path: `.amazonq/rules/${skill.id}.md`,
  body: renderTaskSkillMarkdown(skill, version),
});
