/**
 * The Expo Updates protocol layer for `launch update` — building the update manifest, mapping file
 * extensions to content types, and generating the edge-routing worker + the one-time app config.
 *
 * Launch publishes OTA updates as STATIC files on the user's own bucket (the locked "BYO bucket, no
 * Launch server" decision). But the Expo Updates protocol is header-driven: the `expo-updates` client
 * sends `expo-runtime-version` / `expo-platform` / `expo-channel-name` to one fixed URL and expects the
 * matching manifest back — which a bare bucket can't branch on. So Launch also emits a tiny edge worker
 * (runs in the user's OWN Cloudflare/edge account) that maps those headers to the right static manifest.
 * This module is the pure builder; the `launch update` command exports the bundle, uploads, and signs.
 *
 * NOTE: targets Expo Updates protocol v0 (a JSON manifest + an `expo-signature` header), the simpler of
 * the two protocol versions and what a static-file + thin-worker setup can serve faithfully.
 */

import { extname } from "node:path";

/** One asset (or the launch bundle) in an update manifest: where it lives and what it is. */
export interface ManifestAsset {
  /** Stable key the client uses to cache/dedupe the asset (Launch uses the exported file's basename). */
  key: string;
  /** MIME type, e.g. `application/javascript` for the bundle or `image/png` for an asset. */
  contentType: string;
  /** Public URL the asset is served from. */
  url: string;
  /** File extension without the dot (assets only; omitted for the launch bundle). */
  fileExtension?: string;
}

/** An Expo Updates protocol v0 manifest for one platform + runtime version. */
export interface UpdateManifest {
  /** Unique id for this update (a UUID). */
  id: string;
  /** ISO-8601 creation instant. */
  createdAt: string;
  /** The runtime version this update is compatible with — must match the installed app's. */
  runtimeVersion: string;
  /** The JS bundle to launch. */
  launchAsset: ManifestAsset;
  /** Every other asset (images, fonts) the bundle references. */
  assets: ManifestAsset[];
  /** Reserved protocol fields, kept empty unless a future need appears. */
  metadata: Record<string, never>;
  extra: Record<string, never>;
}

/** Map a file extension to the content type Expo serves it as. The single source for asset typing. */
const CONTENT_TYPES: Record<string, string> = {
  ".js": "application/javascript",
  ".hbc": "application/javascript",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".svg": "image/svg+xml",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

/** Resolve a file's content type from its extension, defaulting to a binary stream. */
export function contentTypeFor(filePath: string): string {
  return CONTENT_TYPES[extname(filePath).toLowerCase()] ?? "application/octet-stream";
}

/** Inputs for {@link assembleManifest}. */
export interface AssembleManifestInput {
  id: string;
  createdAt: string;
  runtimeVersion: string;
  launchAsset: ManifestAsset;
  assets: ManifestAsset[];
}

/** Assemble a protocol-v0 {@link UpdateManifest} from its resolved parts (pure; the command supplies URLs/hashes). */
export function assembleManifest(input: AssembleManifestInput): UpdateManifest {
  return {
    id: input.id,
    createdAt: input.createdAt,
    runtimeVersion: input.runtimeVersion,
    launchAsset: input.launchAsset,
    assets: input.assets,
    metadata: {},
    extra: {},
  };
}

/** The static object key a manifest lives at, keyed by channel + platform + runtime version. */
export function manifestKey(channel: string, platform: string, runtimeVersion: string): string {
  return `updates/${channel}/${platform}/${runtimeVersion}/manifest.json`;
}

/**
 * Generate the Cloudflare Worker that turns the static manifest layout into a protocol-compliant
 * update endpoint. It reads the `expo-*` request headers, fetches the matching static `manifest.json`
 * (and its `.sig` when signed) from `publicBaseUrl`, and returns them with the protocol headers. Runs
 * in the USER's own Cloudflare account — Launch hosts nothing. Deploy its output as a Worker and point
 * the app's `updates.url` at the Worker route.
 */
export function updatesWorkerScript(publicBaseUrl: string): string {
  const base = publicBaseUrl.replace(/\/+$/, "");
  return [
    "// Generated by `launch update` — Expo Updates protocol (v0) router over a static bucket.",
    "// Deploy to your own Cloudflare account and point the app's updates.url at this Worker.",
    `const PUBLIC_BASE = ${JSON.stringify(base)};`,
    "",
    "export default {",
    "  async fetch(request) {",
    "    const runtimeVersion = request.headers.get('expo-runtime-version');",
    "    const platform = request.headers.get('expo-platform');",
    "    const channel = request.headers.get('expo-channel-name') || 'production';",
    "    if (!runtimeVersion || !platform) {",
    "      return new Response('Missing expo-runtime-version / expo-platform', { status: 400 });",
    "    }",
    "    const prefix = `${PUBLIC_BASE}/updates/${channel}/${platform}/${runtimeVersion}`;",
    "    const manifest = await fetch(`${prefix}/manifest.json`);",
    "    if (!manifest.ok) return new Response('No update', { status: 404 });",
    "    const body = await manifest.text();",
    "    const headers = new Headers({",
    "      'content-type': 'application/json; charset=utf-8',",
    "      'expo-protocol-version': '0',",
    "      'expo-sfv-version': '0',",
    "      'cache-control': 'private, max-age=0',",
    "    });",
    "    const sig = await fetch(`${prefix}/manifest.sig`);",
    "    if (sig.ok) headers.set('expo-signature', (await sig.text()).trim());",
    "    return new Response(body, { headers });",
    "  },",
    "};",
  ].join("\n");
}

/** Inputs for {@link updatesAppConfigSnippet}. */
export interface AppConfigSnippetInput {
  /** The Worker route the app polls for updates. */
  updateUrl: string;
  runtimeVersion: string;
  /** Whether updates are code-signed (adds the codeSigning block + cert pointer). */
  signed: boolean;
}

/**
 * The one-time `app.json` `expo.updates` block to print after the first publish, so the developer
 * wires the app to the self-hosted endpoint. Includes the code-signing certificate pointer when signed
 * — without it `expo-updates` would accept any manifest the URL returns.
 */
export function updatesAppConfigSnippet(input: AppConfigSnippetInput): string {
  const updates: Record<string, unknown> = {
    url: input.updateUrl,
    enabled: true,
    fallbackToCacheTimeout: 0,
  };
  if (input.signed) {
    updates["codeSigningCertificate"] = "./certs/launch-code-signing.pem";
    updates["codeSigningMetadata"] = { keyid: "main", alg: "rsa-v1_5-sha256" };
  }
  return JSON.stringify({ expo: { runtimeVersion: input.runtimeVersion, updates } }, null, 2);
}
