/**
 * App Store Connect OpenAPI spec normalization — the pure, testable core of the `gen:asc` vendoring
 * script ({@link file://./../../../scripts/gen-asc-types.ts}). It lives in `src` (not `scripts/`) so
 * typecheck, lint, and tests all cover it; the script itself is a thin I/O orchestrator.
 *
 * Apple publishes the App Store Connect API as a single OpenAPI document inside a zip. Two quirks
 * have to be handled the same way every time we regenerate from it:
 *
 *  1. **Trailing-slash server URL.** `servers[].url` is `https://api.appstoreconnect.apple.com/`.
 *     Joining that with a `/v1/...` path yields a `.com//v1` double slash Apple's gateway rejects —
 *     the same class of bug as the `/v1/v1` double-prefix `ascClient` already guards. We strip it
 *     during vendoring. Note this is hygiene only: `openapi-typescript` emits `paths`/`components`/
 *     `operations` and never `servers`, and the client hardcodes its origin, so the generated types
 *     are byte-identical with or without this step — but it keeps the vendored spec correct for any
 *     future consumer that does read `servers`, and documents the quirk in one place.
 *  2. **Deterministic header.** The banner stamped onto the generated file records the spec's own
 *     `info.version`, never a wall-clock time, so regenerating against an unchanged spec produces a
 *     byte-identical file and the CI drift check (.github/workflows/schema-drift.yml) stays meaningful.
 */

/** Apple's published OpenAPI spec download — a zip containing one `*.oas.json` (plus a macOS fork). */
export const ASC_SPEC_URL =
  "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip";

/** The spec file inside the zip; the archive also carries a `__MACOSX/._*` resource fork we ignore. */
export const ASC_SPEC_FILENAME = "openapi.oas.json";

/**
 * The slice of an OpenAPI document the vendoring step reads or rewrites. Deliberately minimal — typing
 * only these fields keeps this module independent of the code generator's full document type.
 */
export interface AscSpecMeta {
  /** OpenAPI format version, e.g. `"3.0.1"`. */
  openapi: string;
  /** Apple's spec revision, e.g. `"4.4"` — the snapshot identifier stamped into the generated file. */
  info: { version: string };
  /** API origins; Apple ships exactly one, with the trailing slash {@link normalizeAscSpec} strips. */
  servers?: { url: string }[];
}

/**
 * Strip trailing slashes from every `servers[].url` in place (quirk #1) and return the same object so
 * the caller can pass the full, still-typed spec straight on to the code generator.
 */
export function normalizeAscSpec<T extends AscSpecMeta>(spec: T): T {
  for (const server of spec.servers ?? []) {
    server.url = server.url.replace(/\/+$/, "");
  }
  return spec;
}

/**
 * Build the banner prepended to the generated types: marks the file generated (so no one hand-edits
 * it) and records the spec snapshot. Deterministic by design — no timestamp — so an unchanged spec
 * regenerates byte-for-byte (quirk #2).
 */
export function generatedHeader(spec: AscSpecMeta): string {
  return [
    "// AUTOGENERATED by `npm run gen:asc` — do not edit by hand.",
    `// App Store Connect API — OpenAPI ${spec.openapi}, spec version ${spec.info.version}.`,
    "// Source: Apple's published OpenAPI specification (see src/core/asc/specPatch.ts).",
    "",
    "",
  ].join("\n");
}

/**
 * Pick the real spec file from a zip's entry list, skipping the macOS resource-fork sibling
 * (`__MACOSX/._openapi.oas.json`). Returns the matching entry or null when the spec file is absent.
 */
export function pickSpecEntry(entries: string[]): string | null {
  return entries.find((entry) => entry.endsWith(ASC_SPEC_FILENAME) && !entry.includes("__MACOSX")) ?? null;
}
