import { describe, expect, it } from "vitest";
import { generatedHeader, normalizeAscSpec, pickSpecEntry } from "./specPatch.js";

describe("normalizeAscSpec", () => {
  it("strips the trailing slash Apple ships on the server URL", () => {
    const spec = {
      openapi: "3.0.1",
      info: { version: "4.4" },
      servers: [{ url: "https://api.appstoreconnect.apple.com/" }],
    };
    expect(normalizeAscSpec(spec).servers[0]?.url).toBe("https://api.appstoreconnect.apple.com");
  });

  it("collapses repeated trailing slashes and leaves clean URLs untouched", () => {
    const spec = {
      openapi: "3.0.1",
      info: { version: "4.4" },
      servers: [{ url: "https://example.test//" }, { url: "https://clean.test" }],
    };
    expect(normalizeAscSpec(spec).servers.map((server) => server.url)).toEqual([
      "https://example.test",
      "https://clean.test",
    ]);
  });

  it("tolerates a spec with no servers array", () => {
    expect(() => normalizeAscSpec({ openapi: "3.0.1", info: { version: "4.4" } })).not.toThrow();
  });
});

describe("generatedHeader", () => {
  it("stamps the spec version and omits any volatile timestamp (keeps drift checks deterministic)", () => {
    const header = generatedHeader({ openapi: "3.0.1", info: { version: "4.4" } });
    expect(header).toContain("OpenAPI 3.0.1");
    expect(header).toContain("spec version 4.4");
    expect(header).toContain("AUTOGENERATED");
    expect(header).not.toMatch(/\d{4}-\d{2}-\d{2}/);
  });
});

describe("pickSpecEntry", () => {
  it("selects the spec file and ignores the __MACOSX resource fork", () => {
    expect(pickSpecEntry(["__MACOSX/._openapi.oas.json", "openapi.oas.json"])).toBe("openapi.oas.json");
  });

  it("returns null when the spec file is absent", () => {
    expect(pickSpecEntry(["readme.txt"])).toBeNull();
  });
});
