/**
 * `launch agents [init|check]` — scaffold (and verify) cross-agent integration files into the user's
 * app repo, so their coding agent automatically knows how to drive Launch.
 *
 * `init` writes each agent's NATIVE primitive (Claude Skills, Cursor Rules, the `AGENTS.md` Launch
 * section), auto-detecting which agents the repo uses (or `--agent` to pick). Owned files (skills,
 * rules) are rewritten in place; `AGENTS.md` / `CLAUDE.md` get a managed `<!-- launch:start/end -->`
 * block spliced in, so the user's own content is preserved. `check` re-renders and reports any file
 * that drifted or was generated by an older Launch — the freshness gate a consumer can run in CI.
 *
 * All content comes from one typed registry (`core/agents/`), rendered at runtime from the installed
 * version, so the scaffolded files always match the Launch the user actually has.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { Command } from "commander";
import { cancel, confirm, intro, isCancel, multiselect, note, outro } from "@clack/prompts";
import { CONSUMER_SKILLS } from "../../core/agents/registry.js";
import {
  MANAGED_END,
  MANAGED_START,
  renderAgentsBlock,
  renderClaudeMemoryBlock,
  renderClaudeSkillFiles,
  renderCursorBaseRule,
  renderCursorTaskRule,
  spliceManagedBlock,
} from "../../core/agents/render.js";
import type { AgentTarget } from "../../core/agents/types.js";
import { findUnknownCommands } from "../../core/agents/validate.js";

/** The three supported agents, in display order. */
const ALL_TARGETS: AgentTarget[] = ["claude", "cursor", "codex"];

/** Short label per agent for the interactive picker. */
const TARGET_LABELS: Record<AgentTarget, string> = {
  claude: "Claude  (.claude/skills + CLAUDE.md)",
  cursor: "Cursor  (.cursor/rules)",
  codex: "Codex   (AGENTS.md)",
};

/** One planned artifact: an `owned` file rewritten whole, or a `spliced` managed block inside a shared file. */
type Artifact = { kind: "owned"; path: string; body: string } | { kind: "spliced"; path: string; block: string };

/** Flags shared by `init` and `check`. */
interface AgentsOptions {
  /** explicit target list: `claude`, `cursor`, `codex`, `all`, or a comma-separated subset. */
  agent?: string;
  /** non-interactive: skip the confirmation prompt (CI, agents). */
  yes?: boolean;
}

/**
 * Detect which agents a repo already uses, by the files/dirs each leaves behind. `AGENTS.md` counts as
 * Codex (the agent that reads it); a `CLAUDE.md` or `.claude/` counts as Claude; `.cursor/` or a legacy
 * `.cursorrules` counts as Cursor. Heuristic — `--agent` always overrides.
 */
export function detectTargets(cwd: string): AgentTarget[] {
  const has = (relative: string): boolean => existsSync(join(cwd, relative));
  const targets: AgentTarget[] = [];
  if (has(".claude") || has("CLAUDE.md")) targets.push("claude");
  if (has(".cursor") || has(".cursorrules")) targets.push("cursor");
  if (has("AGENTS.md") || has(".codex")) targets.push("codex");
  return targets;
}

/** Parse an explicit `--agent` value into a deduped, validated target list (`all` expands to everything). */
export function parseAgentFlag(value: string): AgentTarget[] {
  const tokens = value
    .split(",")
    .map((t) => t.trim().toLowerCase())
    .filter((t) => t !== "");
  if (tokens.includes("all")) return [...ALL_TARGETS];
  const targets: AgentTarget[] = [];
  for (const token of tokens) {
    if (!ALL_TARGETS.includes(token as AgentTarget)) {
      throw new Error(`Unknown agent "${token}". Use claude, cursor, codex, or all.`);
    }
    if (!targets.includes(token as AgentTarget)) targets.push(token as AgentTarget);
  }
  return targets;
}

/**
 * Plan every artifact to write for the chosen targets. `AGENTS.md` is shared by Codex and Claude (whose
 * `CLAUDE.md` imports it), so it is emitted whenever either is targeted; Claude additionally gets a
 * `CLAUDE.md` block and the Skills, Cursor gets the base rule + one task rule per skill.
 */
export function planArtifacts(targets: AgentTarget[], version: string): Artifact[] {
  const wantClaude = targets.includes("claude");
  const wantCursor = targets.includes("cursor");
  const wantCodex = targets.includes("codex");
  const artifacts: Artifact[] = [];

  if (wantClaude || wantCodex) {
    artifacts.push({ kind: "spliced", path: "AGENTS.md", block: renderAgentsBlock(version) });
  }
  if (wantClaude) {
    artifacts.push({ kind: "spliced", path: "CLAUDE.md", block: renderClaudeMemoryBlock(version) });
    for (const skill of CONSUMER_SKILLS) {
      for (const file of renderClaudeSkillFiles(skill, version)) {
        artifacts.push({ kind: "owned", path: file.path, body: file.body });
      }
    }
  }
  if (wantCursor) {
    const base = renderCursorBaseRule(version);
    artifacts.push({ kind: "owned", path: base.path, body: base.body });
    for (const skill of CONSUMER_SKILLS) {
      const rule = renderCursorTaskRule(skill, version);
      artifacts.push({ kind: "owned", path: rule.path, body: rule.body });
    }
  }
  return artifacts;
}

/** Write the planned artifacts under `cwd`: owned files whole, spliced blocks merged into existing files. */
export function writeArtifacts(cwd: string, artifacts: Artifact[]): void {
  for (const artifact of artifacts) {
    const absolute = join(cwd, artifact.path);
    mkdirSync(dirname(absolute), { recursive: true });
    if (artifact.kind === "owned") {
      writeFileSync(absolute, artifact.body);
    } else {
      const existing = existsSync(absolute) ? readFileSync(absolute, "utf8") : "";
      writeFileSync(absolute, spliceManagedBlock(existing, artifact.block));
    }
  }
}

/** Return the artifacts that are missing or have drifted from a fresh render (the basis for `check`). */
export function findStaleArtifacts(cwd: string, artifacts: Artifact[]): string[] {
  const stale: string[] = [];
  for (const artifact of artifacts) {
    const absolute = join(cwd, artifact.path);
    if (!existsSync(absolute)) {
      stale.push(`${artifact.path} (missing)`);
      continue;
    }
    const current = readFileSync(absolute, "utf8");
    if (artifact.kind === "owned") {
      if (current !== artifact.body) stale.push(artifact.path);
      continue;
    }
    const start = current.indexOf(MANAGED_START);
    const end = current.indexOf(MANAGED_END);
    if (start === -1 || end === -1) {
      stale.push(`${artifact.path} (no Launch block)`);
    } else if (current.slice(start, end + MANAGED_END.length) !== artifact.block) {
      stale.push(artifact.path);
    }
  }
  return stale;
}

/** Throw if the registry names a command the live program no longer has — never scaffold a broken recipe. */
function assertRegistryInSync(program: Command): void {
  const unknown = findUnknownCommands(program);
  if (unknown.length > 0) {
    throw new Error(`Launch's agent registry is out of date with the CLI:\n  ${unknown.join("\n  ")}`);
  }
}

/**
 * Resolve which agents to scaffold for: an explicit `--agent`, else what the repo already uses, else a
 * prompt (interactive) or all three (non-interactive). Prompts only when attached to a TTY and not `--yes`.
 */
async function resolveTargets(cwd: string, options: AgentsOptions): Promise<AgentTarget[]> {
  if (options.agent) return parseAgentFlag(options.agent);
  const detected = detectTargets(cwd);
  if (detected.length > 0) return detected;
  if (options.yes === true || !process.stdin.isTTY) return [...ALL_TARGETS];

  const picked = await multiselect({
    message: "No agent config detected — which agents should Launch set up?",
    options: ALL_TARGETS.map((target) => ({ value: target, label: TARGET_LABELS[target] })),
    initialValues: ALL_TARGETS,
  });
  if (isCancel(picked)) {
    cancel("Cancelled.");
    process.exit(0);
  }
  return picked;
}

/** `launch agents init` — scaffold the integration files into `cwd`. */
async function runInit(program: Command, cwd: string, options: AgentsOptions): Promise<void> {
  assertRegistryInSync(program);
  const targets = await resolveTargets(cwd, options);
  const artifacts = planArtifacts(targets, program.version() ?? "0.0.0");
  const interactive = options.yes !== true && process.stdin.isTTY;

  if (interactive) {
    intro("launch agents");
    note(artifacts.map((a) => `• ${a.path}`).join("\n"), `Will write for: ${targets.join(", ")}`);
    const ok = await confirm({ message: "Write these files?" });
    if (isCancel(ok) || !ok) {
      cancel("Nothing written.");
      process.exit(0);
    }
  }

  writeArtifacts(cwd, artifacts);
  const summary = `Wrote ${artifacts.length} file${artifacts.length === 1 ? "" : "s"} for ${targets.join(", ")}.`;
  if (interactive) {
    outro(summary);
  } else {
    for (const artifact of artifacts) console.log(`✓ ${artifact.path}`);
    console.log(summary);
  }
  console.log("Verify anytime with: launch agents check");
}

/** `launch agents check` — report any scaffolded file that drifted or predates the installed Launch. */
function runCheck(program: Command, cwd: string, options: AgentsOptions): void {
  assertRegistryInSync(program);
  const targets = options.agent ? parseAgentFlag(options.agent) : detectTargets(cwd);
  if (targets.length === 0) {
    console.log("No agent files found. Scaffold them with: launch agents init");
    return;
  }
  const version = program.version() ?? "0.0.0";
  const stale = findStaleArtifacts(cwd, planArtifacts(targets, version));
  if (stale.length === 0) {
    console.log(`Agent files are in sync with launch v${version} (${targets.join(", ")}).`);
    return;
  }
  console.error(`These agent files are out of date — re-run \`launch agents init\`:\n  ${stale.join("\n  ")}`);
  process.exit(1);
}

/** Attach the `agents` command (with `init` and `check`) to the program. */
export function registerAgentsCommand(program: Command): void {
  const agents = program
    .command("agents")
    .description("scaffold agent skills/rules (Claude, Cursor, Codex) so coding agents can drive Launch")
    .action(() => {
      agents.help();
    });

  agents
    .command("init")
    .description("write Claude skills, Cursor rules, and the AGENTS.md Launch section into this repo")
    .option("--agent <list>", "claude | cursor | codex | all (comma-separated; default: auto-detect)")
    .option("-y, --yes", "non-interactive: skip the confirmation prompt (CI, agents)", false)
    .action((options: AgentsOptions) => runInit(program, process.cwd(), options));

  agents
    .command("check")
    .description("verify the scaffolded agent files are in sync with the installed Launch")
    .option("--agent <list>", "claude | cursor | codex | all (comma-separated; default: auto-detect)")
    .action((options: AgentsOptions) => {
      runCheck(program, process.cwd(), options);
    });
}
