/**
 * `launch ci init` — scaffold a GitHub Actions workflow that builds and ships on a hosted runner.
 *
 * The README points no-local-Mac users at GitHub's macOS runners as the free CI path for occasional
 * release builds; this turns that advice into one command. It writes `.github/workflows/launch.yml`
 * wired to the SAME unattended, env-var-driven commands Launch already supports (`creds set-key`,
 * `creds setup`, `doctor`, `build`, each with `--yes`), and documents the exact repository secrets to
 * set. It only writes the workflow file — it never touches credentials or the native project.
 *
 * Why generate YAML instead of shipping a reusable action: a committed workflow is transparent and
 * editable (pin runner images, add caching, change triggers) without depending on a versioned action,
 * and it keeps Launch's only CI surface area a plain file the user owns.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { Command } from 'commander';
import { createLogger } from '../../core/logger.js';

const log = createLogger(false);

/** Repo-relative path of the scaffolded workflow. */
const WORKFLOW_PATH = join('.github', 'workflows', 'launch.yml');

/** Header comment: what this is plus the exact repository secrets each platform needs. */
function header(android: boolean): string {
  const lines = [
    '# Launch — build and ship to the App Store / Play from CI.',
    '#',
    "# Generated by `launch ci init`. GitHub's hosted runners are the free no-local-Mac path the",
    '# Launch README recommends for occasional release builds. Trigger it from the Actions tab',
    '# (Run workflow) or by pushing a version tag.',
    '#',
    '# Required repository secrets — Settings -> Secrets and variables -> Actions:',
    '#   ASC_KEY_ID           App Store Connect API key id (Users & Access -> Integrations -> Keys)',
    '#   ASC_ISSUER_ID        the issuer id shown on that same page',
    '#   ASC_API_KEY_BASE64   base64 of your AuthKey_*.p8:  base64 -i AuthKey_XXXX.p8 | pbcopy',
  ];
  if (android) {
    lines.push(
      '#   PLAY_SERVICE_ACCOUNT_BASE64   base64 of your Play service-account .json',
      '#   ANDROID_KEYSTORE_BASE64       base64 of your upload keystore',
      '#   ANDROID_KEY_ALIAS             the key alias inside that keystore',
      '#   ANDROID_KEYSTORE_PASSWORD     the keystore password',
      '#   ANDROID_KEY_PASSWORD          the key password (often the same)',
    );
  }
  return lines.join('\n');
}

/** The workflow triggers: manual run plus any pushed `v*` tag. */
const TRIGGERS = `name: launch
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:`;

/** The iOS job: macOS runner, decode the ASC key from a secret, then the unattended ship sequence. */
const IOS_JOB = `
  ios:
    name: Build & ship iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install app dependencies
        run: npm ci
      - name: Install Launch
        run: npm install --global launch-store
      - name: Decode the App Store Connect API key
        run: |
          mkdir -p "$RUNNER_TEMP/launch"
          printf '%s' "$ASC_API_KEY_BASE64" | base64 --decode > "$RUNNER_TEMP/launch/AuthKey.p8"
        env:
          ASC_API_KEY_BASE64: \${{ secrets.ASC_API_KEY_BASE64 }}
      - name: Build and upload to TestFlight
        run: |
          launch creds set-key --yes
          launch creds setup --yes
          launch doctor --yes
          launch build ios --yes
        env:
          ASC_KEY_ID: \${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: \${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY_PATH: \${{ runner.temp }}/launch/AuthKey.p8`;

/** The optional Android job: Ubuntu runner + JDK, decode the service account and keystore, then build. */
const ANDROID_JOB = `
  android:
    name: Build & ship Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Install app dependencies
        run: npm ci
      - name: Install Launch
        run: npm install --global launch-store
      - name: Decode the Play service account and upload keystore
        run: |
          mkdir -p "$RUNNER_TEMP/launch"
          printf '%s' "$PLAY_SERVICE_ACCOUNT_BASE64" | base64 --decode > "$RUNNER_TEMP/launch/play.json"
          printf '%s' "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$RUNNER_TEMP/launch/upload.keystore"
        env:
          PLAY_SERVICE_ACCOUNT_BASE64: \${{ secrets.PLAY_SERVICE_ACCOUNT_BASE64 }}
          ANDROID_KEYSTORE_BASE64: \${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Build and upload to Google Play
        run: |
          launch creds set-key --platform android "$RUNNER_TEMP/launch/play.json" --yes
          launch creds setup --platform android --import "$RUNNER_TEMP/launch/upload.keystore" --alias "$ANDROID_KEY_ALIAS" --yes
          launch build android --yes
        env:
          PLAY_SERVICE_ACCOUNT: \${{ runner.temp }}/launch/play.json
          ANDROID_KEY_ALIAS: \${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: \${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: \${{ secrets.ANDROID_KEY_PASSWORD }}`;

/** Render the full `launch.yml`, including the Android job only when asked. */
export function workflowYaml(options: { android: boolean }): string {
  const jobs = options.android ? `${IOS_JOB}\n${ANDROID_JOB}` : IOS_JOB;
  return `${header(options.android)}\n\n${TRIGGERS}\n${jobs}\n`;
}

/** Print the secrets the user still has to set, so the workflow isn't a silent dead end. */
function printNextSteps(android: boolean): void {
  log.line(`✓ Wrote ${WORKFLOW_PATH}`);
  log.line('\nSet these repository secrets (Settings -> Secrets and variables -> Actions):');
  log.line('  • ASC_KEY_ID, ASC_ISSUER_ID');
  log.line('  • ASC_API_KEY_BASE64    base64 -i AuthKey_XXXX.p8 | pbcopy');
  if (android) {
    log.line('  • PLAY_SERVICE_ACCOUNT_BASE64, ANDROID_KEYSTORE_BASE64');
    log.line('  • ANDROID_KEY_ALIAS, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_PASSWORD');
  }
  log.line('\nThen push a v* tag (or use Run workflow) to build and ship.');
}

/** Attach the `ci` command (with the `init` subcommand) to the program. */
export function registerCiCommand(program: Command): void {
  program
    .command('ci')
    .description('scaffold CI workflows for building & shipping Launch apps')
    .command('init')
    .description('write a GitHub Actions workflow that builds and ships on a hosted runner')
    .option('--android', 'also emit an Android job (Ubuntu runner)', false)
    .option('--force', 'overwrite an existing .github/workflows/launch.yml', false)
    .action((options: { android: boolean; force: boolean }) => {
      const path = join(process.cwd(), WORKFLOW_PATH);
      if (existsSync(path) && !options.force) {
        throw new Error(`${WORKFLOW_PATH} already exists. Re-run with --force to overwrite it.`);
      }
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, workflowYaml({ android: options.android }));
      printNextSteps(options.android);
    });
}
