import { describe, expect, it } from "vitest";
import {
  CANONICAL_SENTENCE,
  type CommandSpec,
  type DocStats,
  IS_NOT_SIGNATURE,
  countAsyncMethods,
  countTestCases,
  renderCommandReference,
  renderLlmsFull,
  renderLlmsTxt,
} from "./commandDocs.js";

const STATS: DocStats = { commands: 2, operations: 203, tests: 920 };

/** A tiny two-command tree: one leaf with flags, one parent with a subcommand — covers every render branch. */
const SAMPLE: CommandSpec[] = [
  {
    path: "build",
    args: "<platform>",
    description: "run the full pipeline",
    options: [
      { flags: "-p, --profile <name>", description: "build profile" },
      { flags: "--bump <kind>", description: "version bump: patch|minor|major" },
    ],
    subcommands: [],
  },
  {
    path: "metadata",
    args: "",
    description: "sync the store listing",
    options: [],
    subcommands: [
      { path: "metadata pull", args: "", description: "download the live listing", options: [], subcommands: [] },
    ],
  },
];

describe("renderCommandReference", () => {
  const md = renderCommandReference(SAMPLE, STATS);

  it("opens with the do-not-edit banner so nobody hand-edits the generated file", () => {
    expect(md.startsWith("<!-- AUTOGENERATED by `npm run docs:gen`")).toBe(true);
  });

  it("puts the live stats in the headline blockquote", () => {
    expect(md).toContain("**203 App Store Connect & Google Play API operations** across **2 commands**");
    expect(md).toContain("guarded by **920 tests**");
  });

  it("renders a top-level command at h2 with its argument usage", () => {
    expect(md).toContain("## `launch build <platform>`");
  });

  it("renders a subcommand at h3 under its parent's full path", () => {
    expect(md).toContain("## `launch metadata`");
    expect(md).toContain("### `launch metadata pull`");
  });

  it("escapes pipes in flag descriptions so the markdown table doesn't break", () => {
    expect(md).toContain("version bump: patch\\|minor\\|major");
  });

  it("omits the flag table for a command with no options", () => {
    const metadataSection = md.slice(md.indexOf("## `launch metadata`"), md.indexOf("### `launch metadata pull`"));
    expect(metadataSection).not.toContain("| Flag |");
  });
});

describe("renderLlmsTxt", () => {
  const txt = renderLlmsTxt(STATS);

  it("leads with the canonical sentence as the llmstxt.org summary blockquote", () => {
    expect(txt).toContain(`> ${CANONICAL_SENTENCE}`);
  });

  it("links the generated command reference with the live command count", () => {
    expect(txt).toContain("[Command reference](./docs/commands.md): all 2 `launch` commands");
  });
});

describe("renderLlmsFull", () => {
  const full = renderLlmsFull(SAMPLE, STATS);

  it("carries the what-Launch-is-not disambiguation for AI engines", () => {
    expect(full).toContain(IS_NOT_SIGNATURE);
  });

  it("lists every command, nesting subcommands under their parent", () => {
    expect(full).toContain("- `launch build <platform>` — run the full pipeline");
    expect(full).toContain("- `launch metadata` — sync the store listing");
    expect(full).toContain("  - `launch metadata pull` — download the live listing");
  });
});

describe("countAsyncMethods", () => {
  it("counts public async methods and ignores private ones and bare keywords", () => {
    const source = [
      "class Client {",
      "  async listApps() {}",
      "  async getApp(id) {}",
      "  private async refreshToken() {}",
      "  build() { const x = async () => 1; }",
      "}",
    ].join("\n");
    expect(countAsyncMethods(source)).toBe(2);
  });
});

describe("countTestCases", () => {
  it("counts it/test calls (incl. .each/.skip) and ignores describe", () => {
    const a = ['describe("x", () => {', '  it("a", () => {});', '  test("b", () => {});', "});"].join("\n");
    const b = ['it.each([1])("c", () => {});', 'it.skip("d", () => {});'].join("\n");
    expect(countTestCases([a, b])).toBe(4);
  });
});
