import { describe, expect, it } from "vitest";
import {
  CANONICAL_SENTENCE,
  type CommandSpec,
  type DocStats,
  FAQ_REGION_END,
  FAQ_REGION_START,
  FAQ_SIGNATURE,
  GENERATIVE_AI_FAQ,
  IS_NOT_SIGNATURE,
  STATS_BADGES_END,
  STATS_BADGES_START,
  countAsyncMethods,
  countTestCases,
  renderCommandReference,
  renderFaqRegion,
  renderLlmsTxt,
  renderStatsBadges,
  spliceReadmeBadges,
  spliceReadmeFaq,
} from "./commandDocs.js";

const STATS: DocStats = { commands: 2, operations: 203, tests: 920 };

/** A tiny two-command tree: one leaf with flags, one parent with a subcommand — covers every render branch. */
const SAMPLE: CommandSpec[] = [
  {
    path: "build",
    args: "<platform>",
    description: "run the full pipeline",
    options: [
      { flags: "-p, --profile <name>", description: "build profile" },
      { flags: "--bump <kind>", description: "version bump: patch|minor|major" },
    ],
    subcommands: [],
  },
  {
    path: "metadata",
    args: "",
    description: "sync the store listing",
    options: [],
    subcommands: [
      { path: "metadata pull", args: "", description: "download the live listing", options: [], subcommands: [] },
    ],
  },
];

describe("renderCommandReference", () => {
  const md = renderCommandReference(SAMPLE, STATS);

  it("opens with the do-not-edit banner so nobody hand-edits the generated file", () => {
    expect(md.startsWith("<!-- AUTOGENERATED by `npm run docs:gen`")).toBe(true);
  });

  it("puts the live stats in the headline blockquote", () => {
    expect(md).toContain("**203 App Store Connect & Google Play API operations** across **2 commands**");
    expect(md).toContain("guarded by **920 tests**");
  });

  it("renders a top-level command at h2 with its argument usage", () => {
    expect(md).toContain("## `launch build <platform>`");
  });

  it("renders a subcommand at h3 under its parent's full path", () => {
    expect(md).toContain("## `launch metadata`");
    expect(md).toContain("### `launch metadata pull`");
  });

  it("escapes pipes in flag descriptions so the markdown table doesn't break", () => {
    expect(md).toContain("version bump: patch\\|minor\\|major");
  });

  it("omits the flag table for a command with no options", () => {
    const metadataSection = md.slice(md.indexOf("## `launch metadata`"), md.indexOf("### `launch metadata pull`"));
    expect(metadataSection).not.toContain("| Flag |");
  });
});

describe("renderLlmsTxt (the merged single AI-facing file)", () => {
  const txt = renderLlmsTxt(SAMPLE, STATS);

  it("leads with the canonical sentence as the llmstxt.org summary blockquote", () => {
    expect(txt).toContain(`> ${CANONICAL_SENTENCE}`);
  });

  it("carries the what-Launch-is-not disambiguation for AI engines", () => {
    expect(txt).toContain(IS_NOT_SIGNATURE);
  });

  it("carries the generative-AI FAQ so engines can lift the EAS-alternative answers", () => {
    expect(txt).toContain("## FAQ");
    expect(txt).toContain(FAQ_SIGNATURE);
  });

  it("inlines every command, nesting subcommands under their parent", () => {
    expect(txt).toContain("- `launch build <platform>` — run the full pipeline");
    expect(txt).toContain("- `launch metadata` — sync the store listing");
    expect(txt).toContain("  - `launch metadata pull` — download the live listing");
  });

  it("links the generated command reference with the live command count", () => {
    expect(txt).toContain("[Command reference](./docs/commands.md): all 2 `launch` commands");
  });
});

describe("renderStatsBadges", () => {
  const block = renderStatsBadges(STATS);

  it("is fenced by the markers so docs:gen can splice it back in", () => {
    expect(block.startsWith(STATS_BADGES_START)).toBe(true);
    expect(block.endsWith(STATS_BADGES_END)).toBe(true);
  });

  it("bakes the live operation count into the endpoint badge", () => {
    expect(block).toContain("store%20API-203%20endpoints");
  });

  it("bakes the live test count into the tests badge", () => {
    expect(block).toContain("tests-920%20passing");
  });

  it("renders a qualitative CRUD badge that carries no number to go stale", () => {
    expect(block).toContain("CRUD-full%20lifecycle");
  });
});

describe("spliceReadmeBadges", () => {
  const readme = ["# Launch", "", STATS_BADGES_START, "", "<p>stale</p>", "", STATS_BADGES_END, "", "Body."].join("\n");

  it("replaces the whole fenced region with the freshly rendered badges", () => {
    const spliced = spliceReadmeBadges(readme, renderStatsBadges(STATS));
    expect(spliced).toContain("tests-920%20passing");
    expect(spliced).not.toContain("<p>stale</p>");
    expect(spliced.startsWith("# Launch")).toBe(true);
    expect(spliced.endsWith("Body.")).toBe(true);
  });

  it("throws when the markers are missing rather than dropping the badges", () => {
    expect(() => spliceReadmeBadges("# Launch\n\nNo markers here.", "x")).toThrow(/stats-badges markers/);
  });
});

describe("renderFaqRegion", () => {
  const block = renderFaqRegion();

  it("is fenced by the FAQ markers so docs:gen can splice it back in", () => {
    expect(block.startsWith(FAQ_REGION_START)).toBe(true);
    expect(block.endsWith(FAQ_REGION_END)).toBe(true);
  });

  it("carries the generative-AI FAQ verbatim, so the README and llms.txt share one source", () => {
    expect(block).toContain(GENERATIVE_AI_FAQ);
    expect(block).toContain(FAQ_SIGNATURE);
  });
});

describe("spliceReadmeFaq", () => {
  const readme = ["# Launch", "", FAQ_REGION_START, "", "stale Q&A", "", FAQ_REGION_END, "", "Body."].join("\n");

  it("replaces the whole fenced FAQ region with the freshly rendered block", () => {
    const spliced = spliceReadmeFaq(readme, renderFaqRegion());
    expect(spliced).toContain(FAQ_SIGNATURE);
    expect(spliced).not.toContain("stale Q&A");
    expect(spliced.startsWith("# Launch")).toBe(true);
    expect(spliced.endsWith("Body.")).toBe(true);
  });

  it("throws when the FAQ markers are missing rather than dropping the FAQ", () => {
    expect(() => spliceReadmeFaq("# Launch\n\nNo markers here.", "x")).toThrow(/faq markers/);
  });
});

describe("countAsyncMethods", () => {
  it("counts public async methods and ignores private ones and bare keywords", () => {
    const source = [
      "class Client {",
      "  async listApps() {}",
      "  async getApp(id) {}",
      "  private async refreshToken() {}",
      "  build() { const x = async () => 1; }",
      "}",
    ].join("\n");
    expect(countAsyncMethods(source)).toBe(2);
  });
});

describe("countTestCases", () => {
  it("counts it/test calls (incl. .each/.skip) and ignores describe", () => {
    const a = ['describe("x", () => {', '  it("a", () => {});', '  test("b", () => {});', "});"].join("\n");
    const b = ['it.each([1])("c", () => {});', 'it.skip("d", () => {});'].join("\n");
    expect(countTestCases([a, b])).toBe(4);
  });
});
