name: Docs in sync
'on':
  workflow_call: null
permissions:
  contents: read
jobs:
  docs:
    name: Docs are in sync with the CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup workspace
        uses: ./.github/actions/setup
      - run: pnpm docs:check
    timeout-minutes: 15
